### ISSUE TITLE
remotebuild is not extracting all files from the upload_BUILDNUM.tgz

### ISSUE THREAD

**Issue by sdhintGIT** [Microsoft/TACO#106]
I had originally thought that my plugin folders/files were not getting copied from the windows machine over to the mac, but I found them inside the upload_BUILD.tgz they are just not getting extracted before building.

is there a configuration or some file i can update to make sure all files are extracted?

I installed remotebuild today on the mac, version 2.0.1 , running same node version as my windows machine, 0.12.2 

any help is appreciated, it's literally driving me nuts. vs-mda-remote was previously installed on this machine as i was an early adopter of cordova tools in vs2013.

**Comment by MSLaguana** [comment]
We treat the /plugins folder as special when uploading files to make sure that we install/uninstall/update plugins appropriately, but there could be a bug here.

Instead of extracting directly to /plugins, we extract to /remote/plugins, and then go and invoke "cordova plugin add /remote/plugins/thePlugin" if it is a new plugin (if the plugin.xml is new) or we copy the files to /plugins/thePlugin if the plugin already existed.

Could you please give some more details about what's happening? Is nothing at all being added to /plugins/ ?

**Comment by sdhintGIT** [comment]
On the mac in builds/BUILDNUM/cordovaApp  it creates a plugins folder and there is one plugin there.  cordova-plugin-whitelist, fetch.json, ios.json and .DS_Store
In /builds/BUILDNUM/cordovaApp/www there is no plugins folder

On the windows machine, it’s correctly built in platforms,
[cid:image001.png@01D10DB0.6622FFF0]

[cid:image002.png@01D10DB0.6622FFF0]


and is also in the .tgz on the mac, just not extracted. To cordovaApp


I can send you the .tgz if it would help with getting this fixed. I have to have this working.
I have tried:
Removing the ios platform through command line and reading it, removing all plugins and reinstalling them after blowing away the ios platform, still didn’t take.


It was working fine with vs2013 and vs-mda-remote for months and months.


_________________________

SAMANTHA ALDRIDGE
Software Architect
Finished Vehicle Logistics

502.570.3302  direct
859.433.3287  cell
502.570.4302 fax
Email saldridge@vascorlogistics.com<mailto:saldridge@vascorlogistics.com>

VASCOR, Ltd.
100 Farmers Bank Drive
Suite 300
Georgetown, KY 40324
www.vascorlogistics.com<http://www.vascorlogistics.com/>

**Comment by sdhintGIT** [comment]
Also, there is nothing in the ‘remote’ folder of the extracted cordovaApp folder, it’s empty

_________________________

SAMANTHA ALDRIDGE
Software Architect
Finished Vehicle Logistics

502.570.3302  direct
859.433.3287  cell
502.570.4302 fax
Email saldridge@vascorlogistics.com<mailto:saldridge@vascorlogistics.com>

VASCOR, Ltd.
100 Farmers Bank Drive
Suite 300
Georgetown, KY 40324
www.vascorlogistics.com<http://www.vascorlogistics.com/>

**Comment by MSLaguana** [comment]
Sending the .tgz would be helpful; you can send it to jithomso@microsoft.com. I'll try to see if I can get you a workaround, as well as fixing the underlying issue.

**Comment by MSLaguana** [comment]
We've just published taco-remote@1.1.2 which fixes this issue. Any new installs of remotebuild should have the fix, and you can also go to the remotebuild install location and `npm upgrade taco-remote` to upgrade it to the fixed version.
