### ISSUE TITLE
How to enable an existing project?

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/TACO#132]
Hi guys,

Is possible to enable taco for an existing project?

Regards

**Comment by nisheetjain** [comment]
Can you clarify what you meant by "enable"? Do you want to use taco kits features? 
If yes you can use following command to target a 2.0.0 kit

"taco kit select --kit tacokit@2.0.0"

**Comment by ThorstenHans** [comment]
I think @jdnichollsc wants to take an existing cordova project and "tacofy" it. 

Actually there is nothing required, you can just opt in at any point. afaik you don't have to create the project explicitly with `taco create` just navigate within your project folder and start using `taco`

**Comment by nisheetjain** [comment]
Thanks @ThorstenHans. you are right, you don't really need a taco created project to using other taco features.  you can just install taco-cli via npm and start using taco.

if you specifically need to use the kits feature, you can make your existing project target a certain kit using "taco kit select --kit tacokit@2.0.0"

**Comment by nisheetjain** [comment]
@jdnichollsc closing this issue. feel free to reopen this issue or create a new one if the resolution isn't correct

**Comment by slorber** [comment]
@nisheetjain I think this should be put in the doc on how to add TACO to an existing cordova project. Not all cordova projects are new projects, and it would help if we could simplify community adoption of TACO to document this better
