### ISSUE TITLE
livereload sporadically fails on file change

### ISSUE THREAD

**Issue by joshuaskelton** [Microsoft/TACO#246]
Once in a while I run across the below error message while updating files during a livereload session. I've confirmed that I'm not able to remove the offending file even with admin permissions. This is only an issue on Windows.

I can redeploy my app and things seem to be back in a good state.

> rm: could not remove directory (code ENOTEMPTY): C:\Repos\test_livereload_project_0\platforms\android\assets\www
>
> mkdir: path already exists: C:\Repos\test_livereload_project_0\platforms\android\assets\www
> 
> cp: copyFileSync: could not write to dest file (code=EPERM):C:\Repos\test_livereload_project_0\platforms\android\assets\www\index.html
> 
>  - An error occurred: Error: EPERM, operation not permitted 'C:\Repos\test_livereload_project_0\platforms\android\assets\www\index.html'

**Comment by sushruth** [comment]
This is more often to me than not. Exact same problem here too.

**Comment by omefire** [comment]
Could it be due to the fact that you might have the same files opened by another process (possibly another console tab) ?

**Comment by sushruth** [comment]
No the error persisted even after a restart.

**Comment by aunz** [comment]
@omefire, I also ran into EPERM, probably as you mentioned, the file is opened by another process.
I have webpack to watch my `appRoot/src/client/entry.js` and compile to `appRoot/myTacoApp/www/js/index.js`. The errors are sporadic. I am on Windows 10 with webpack 2.x. I am not sure if this is specific to webpack or Taco. Do you have any recommendation for this setup. Thanks a lot!

**Comment by sushruth** [comment]
In my case this was caused by having my code editor open, but that does not sound like its normal.
