### ISSUE TITLE
Can't run with --livereload missing taco.json

### ISSUE THREAD

**Issue by csantanapr** [Microsoft/TACO#265]
I have a plain cordova app I create with cordova create
When I run taco run --livereload I get error about taco.json missing

$ taco run --livereload
Setting up livereload ...
Error: live-reload is not supported for project without taco.json

How do I generate a simple taco.json?

**Comment by MSLaguana** [comment]
You need to pick what version of cordova you want to use with the project, and then do `taco kit select --cordova 6.0.0` or similar. Alternately, if you want to use a kit you can do `taco kit select --kit tacokit@3.0.0` or similar

**Comment by akofman** [comment]
I'm in the same case and don't really understand how to create this taco.json file :(
I tried to create it and to add cordova 6.1.1 but it changes nothing. Thought ?

Is there a documentation about this file ? (sorry if I didn't find it)

**Comment by MSLaguana** [comment]
Did you try running the commands mentioned just above: `taco kit select --cordova 6.1.1` ?

**Comment by akofman** [comment]
I did. Without an empty valid json file, I get the same error message. With an empty json file like `{}`, it just happens nothing.

**Comment by MSLaguana** [comment]
Hmm, I just checked myself and it looks like something has broken there.

You can manually create a taco.json file containing `{"cordova-cli": "6.1.1"}` and that should suffice for livereload.

**Comment by akofman** [comment]
No problem ! It's better now, thanks for your help.

**Comment by MSLaguana** [comment]
I've now published an updated `taco-cli` so `taco kit select --cordova <version>` should work once again.
