### ISSUE TITLE
cordova version 5.4.1 build success, cordova ver 6.0 build fail.

### ISSUE THREAD

**Issue by sargin48** [Microsoft/TACO#268]
Hi everybody.

i can build from Visual Studio Javascript Cordova project 5.4.1 build successfull.
when try build cordova version 6.0   give error.

on mac
remotebuild version 2.1.1

<img width="1440" alt="screen shot 2016-02-25 at 23 46 00" src="https://cloud.githubusercontent.com/assets/3220540/13335559/57e4d092-dc1a-11e5-9032-cb46a0ab4ac8.png">
![adsiz](https://cloud.githubusercontent.com/assets/3220540/13335560/59783700-dc1a-11e5-9378-61e91b66f081.png)

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Remote build error from the build server Build failed with error Error code 65 for command: xcodebuild with args: -xcconfig,/Users/SARGIN/.taco_home/remote-builds/taco-remote/builds/2246/cordovaApp/platforms/ios/cordova/build-release.xcconfig,-project,Rapor Ideaktif.xcodeproj,ARCHS=armv7 arm64,-target,Rapor Ideaktif,-configuration,Release,-sdk,iphoneos,build,VALID_ARCHS=armv7 arm64,CONFIGURATION_BUILD_DIR=/Users/SARGIN/.taco_home/remote-builds/taco-remote/builds/2246/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/SARGIN/.taco_home/remote-builds/taco-remote/builds/2246/cordovaApp/platforms/ios/build/sharedpch: {1}	sirketim.ui.phone	C:\ideaktif\sirketim-rapor-mobil\sirketim.ui.phone\MDAVSCLİ	1	
```

**Comment by MSLaguana** [comment]
Could you please open up the "output" window in VS and look towards the bottom for the specific error? Alternately look in `~/.taco_home/remote-builds/taco-remote/builds/<build number>/build.log` for the same information.

**Comment by michschu** [comment]
@MSLaguana: I am facing the same problem like @sargin48 under the same conditions (upgrade from Cordova 5.4.1 to 6.0.0) and will see to provide the requested information this evening. However what do you expect from it?

**Comment by MSLaguana** [comment]
The error reported above is the generic "Something went wrong with the build", but typically a few lines above that in the output log there is a more specific error saying exactly what the error was. Based on that error we can troubleshoot further.

**Comment by michschu** [comment]
The log file contains more than 800 lines. Therefore I have uploaded it to this [link](http://1drv.ms/1LPefme).

Please lemme know, if access works (or not).

**Comment by MSLaguana** [comment]
Looks like I end up viewing a blank file. Try including the final ~30 or so lines in here, it should be right at the end.

**Comment by michschu** [comment]
I have corrected the link now. Please try again. Sorry for the circumstances.

**Comment by MSLaguana** [comment]
Now it requires logging in.

**Comment by michschu** [comment]
Oh dear...

Okay, here are the last log lines:
_1>
1>  ** BUILD FAILED **
1>
1>
1>  The following build commands failed:
1>  	CompileC build/My-Project.build/Debug-iphoneos/My-Project.build/Objects-normal/armv7/InAppPurchase.o My-Project/Plugins/cc.fovea.cordova.purchase/InAppPurchase.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
1>  (1 failure)
1>  ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/cordova/build-debug.xcconfig,-project,My-Project.xcodeproj,ARCHS=armv7 arm64,-target,My-Project,-configuration,Debug,-sdk,iphoneos,build,VALID_ARCHS=armv7 arm64,CONFIGURATION_BUILD_DIR=/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/sharedpch
1>  You may not have the required environment or OS to build this project
1>  Fehler beim Erstellen der App für die "BuildNumber" 92902: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/cordova/build-debug.xcconfig,-project,My-Project.xcodeproj,ARCHS=armv7 arm64,-target,My-Project,-configuration,Debug,-sdk,iphoneos,build,VALID_ARCHS=armv7 arm64,CONFIGURATION_BUILD_DIR=/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/sharedpch
1>MDAVSCLI : error : Remote build error from the build server Build failed with error Error code 65 for command: xcodebuild with args: -xcconfig,/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/cordova/build-debug.xcconfig,-project,My-Project.xcodeproj,ARCHS=armv7 arm64,-target,My-Project,-configuration,Debug,-sdk,iphoneos,build,VALID_ARCHS=armv7 arm64,CONFIGURATION_BUILD_DIR=/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/sharedpch: {1}
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========_

**Comment by MSLaguana** [comment]
We need the lines just before that, above the ** BUILD FAILED **. There should be some lines up there (likely indented) which refer to a specific error.

**Comment by michschu** [comment]
_1>  CompileC build/My-Project.build/Debug-iphoneos/My-Project.build/Objects-normal/armv7/CDVStatusBar.o My-Project/Plugins/cordova-plugin-statusbar/CDVStatusBar.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
1>      cd /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios
1>      export LANG=en_US.US-ASCII
1>      export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/michael/.taco_home/node_modules/taco-remote-lib/2.1.1/node_modules/taco-remote-lib/node_modules/.bin:/Users/michael/.nvm/versions/node/v0.12.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Users/michael/npm/bin:/Users/michael/Library/Android/sdk/platform-tools:/Users/michael/Library/Android/sdk/tools"
1>      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/_k/b_l2pz895dg7yp5qwhwylxgw0000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/My-Project-generated-files.hmap -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/My-Project-own-target-headers.hmap -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/My-Project-all-target-headers.hmap -iquote /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/My-Project-project-headers.hmap -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/device/include -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/device/usr/local/lib/include -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/UninstalledProducts/include -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/UninstalledProducts/iphoneos/include -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/device -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/DerivedSources/armv7 -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/DerivedSources -F/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/device -include /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/sharedpch/My-Project-Prefix-fjaekyzcyjibfldabpjqezyqxrtd/My-Project-Prefix.pch -MMD -MT dependencies -MF /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/Objects-normal/armv7/CDVStatusBar.d --serialize-diagnostics /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/Objects-normal/armv7/CDVStatusBar.dia -c /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/My-Project/Plugins/cordova-plugin-statusbar/CDVStatusBar.m -o /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/Objects-normal/armv7/CDVStatusBar.o
1>
1>  CompileC build/My-Project.build/Debug-iphoneos/My-Project.build/Objects-normal/armv7/IonicKeyboard.o My-Project/Plugins/ionic-plugin-keyboard/IonicKeyboard.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
1>      cd /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios
1>      export LANG=en_US.US-ASCII
1>      export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/michael/.taco_home/node_modules/taco-remote-lib/2.1.1/node_modules/taco-remote-lib/node_modules/.bin:/Users/michael/.nvm/versions/node/v0.12.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Users/michael/npm/bin:/Users/michael/Library/Android/sdk/platform-tools:/Users/michael/Library/Android/sdk/tools"
1>      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/_k/b_l2pz895dg7yp5qwhwylxgw0000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/My-Project-generated-files.hmap -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/My-Project-own-target-headers.hmap -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/My-Project-all-target-headers.hmap -iquote /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/My-Project-project-headers.hmap -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/device/include -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/device/usr/local/lib/include -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/UninstalledProducts/include -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/UninstalledProducts/iphoneos/include -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/device -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/DerivedSources/armv7 -I/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/DerivedSources -F/Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/device -include /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/sharedpch/My-Project-Prefix-fjaekyzcyjibfldabpjqezyqxrtd/My-Project-Prefix.pch -MMD -MT dependencies -MF /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/Objects-normal/armv7/IonicKeyboard.d --serialize-diagnostics /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/Objects-normal/armv7/IonicKeyboard.dia -c /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/My-Project/Plugins/ionic-plugin-keyboard/IonicKeyboard.m -o /Users/michael/.taco_home/remote-builds/taco-remote/builds/92902/cordovaApp/platforms/ios/build/My-Project.build/Debug-iphoneos/My-Project.build/Objects-normal/armv7/IonicKeyboard.o
1>
1>  ** BUILD FAILED **_

Better?

**Comment by MSLaguana** [comment]
A colleaegue has just pointed out that your one drive link does in fact work, just not in the browser I was trying. Apologies for the trouble.

If you scroll further back than I expected, around line 766 you'll find an error `1 error generated` pointing out a missing import. It sounds like you may have a plugin which is misconfigured or broken.

**Comment by michschu** [comment]
@MSLaguana: Thanks a bunch. It seems, you have nailed it down as the was a problem with the plugin cc.fovea.cordova.purchase existing (wrong old version). 

However when deploying now I receive at a late point the warning "Timed out launching the app. Check your network connection to the mac and try again. If you are launching to a device, make sure you have Web Inspector enabled on it."			

Could you please help furthermore? Or do you want me to open a new thread here on GitHub for this?
