### ISSUE TITLE
livereload not working with 6.0.0

### ISSUE THREAD

**Issue by csantanapr** [Microsoft/TACO#269]
On Mac 10.11.3

running taco --livereload browsersync runs, but after ios app starts taco exists and kills browsersync process

$ taco create tacoapp
$ cd tacoapp
$ taco kit select --cordova 6.0.0
Cordova CLI: 5.4.1 => 6.0.0

Success!
$ taco platform add ios
Adding ios project...
iOS project created with cordova-ios@4.0.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for ios
Success! Platform(s) ios added to the project.

$ taco platform ls
Installed platforms: ios 4.0.1
Available platforms: amazon-fireos, android, blackberry10, browser, firefoxos, osx, webos
Remote platforms:
$ taco emulate ios --livereload
...

...

io.taco.hellotaco: 9544
logPath: /Users/<username>/Desktop/testing/8.0/0225/tacoapp3/platforms/ios/cordova/console.log
~/Desktop/testing/8.0/0225/tacoapp3
$

**Comment by csantanapr** [comment]
bump Any news when this will be fix?

**Comment by csantanapr** [comment]
Same problem using cordova@6.1.0

```bash
🍰  $ taco kit select --cordova 6.1.0


Cordova CLI: 5.4.1 => 6.1.0

Success!

~/foo/tacoapp
🍰  $ taco platform add ios

Downloading: cordova@6.1.0
cordova@6.1.0 ../../.taco_home/node_modules/cordova/6.1.0/node_modules/cordova
├── underscore@1.7.0
├── q@1.0.1
├── ansi@0.3.1
├── nopt@3.0.1 (abbrev@1.0.7)
├── cordova-common@1.1.1 (cordova-registry-mapper@1.1.15, unorm@1.4.1, underscore@1.8.3, q@1.4.1, semver@5.1.0, shelljs@0.5.3, osenv@0.1.3, bplist-parser@0.1.1, glob@5.0.15, elementtree@0.1.6, plist@1.2.0)
├── update-notifier@0.5.0 (is-npm@1.0.0, semver-diff@2.1.0, repeating@1.1.3, string-length@1.0.1, chalk@1.1.3, configstore@1.4.0, latest-version@1.0.1)
└── cordova-lib@6.1.0 (valid-identifier@0.0.1, opener@1.4.1, properties-parser@0.2.3, semver@4.3.6, shelljs@0.3.0, nopt@3.0.6, cordova-app-hello-world@3.10.0, dep-graph@1.1.0, xcode@0.8.0, aliasify@1.9.0, init-package-json@1.9.3, tar@1.0.2, request@2.47.0, npm@2.15.2, cordova-serve@1.0.0, cordova-js@4.1.4)

cordova@6.1.0 downloaded and installed.
Adding ios project...
iOS project created with cordova-ios@4.1.0
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for ios
Success! Platform(s) ios added to the project.


Quick tips & commands:
 * Install the build tools for each platform:  taco install-reqs <PLATFORM>
 * Add a Cordova plugin: taco plugin add <PLUGIN-ID>
 * Connect to a remote build agent: taco remote add <PLATFORM>
 * Build your app: taco build <PLATFORM>
 * Run your app in the emulator: taco emulate <PLATFORM>
 * Run your app on a device: taco run <PLATFORM>

For command help, use 'taco help'
For full documentation online, use 'taco docs'

~/foo/tacoapp
🍰  $ taco run ios --livereload
...
** BUILD SUCCEEDED **

No target specified for emulator. Deploying to iPhone-6s-Plus, 9.3 simulator

TACO Live Reload started.

Press CTRL+C to exit

io.taco.hellotaco: 5247
logPath: /Users/csantana23/foo/tacoapp/platforms/ios/cordova/console.log
~/foo/tacoapp
🍰  $ taco -v
1.2.0
```

**Comment by tgensol** [comment]
+1

**Comment by ridomin** [comment]
+1

**Comment by andrinallc** [comment]
+1

**Comment by jabracadabra** [comment]
+1

**Comment by adamiprinciples** [comment]
Its specifically the cordova-ios version : https://github.com/Microsoft/TACO/issues/295

**Comment by csantanapr** [comment]
Yes I already know that, tell me how to fix it. 
cordova-ios is not the problem taco CLI needs to be updated to work correctly with the new major version of cordova-ios@4

**Comment by csantanapr** [comment]
@adamiprinciples I work around the issue by creating my own livereload tool 😉 here https://www.npmjs.com/package/cdvlive

**Comment by pfeilbr** [comment]
+ 1
same issue

![](http://static-content-01.s3-website-us-east-1.amazonaws.com/taco-playground_—_-bash_—_80×24_and_index_js_—__Users_pfeilbr_Dropbox_mac01_Users_brianpfeil_projects_taco-playground_1CEF80DE.png)

used @csantanapr cdlive module in the meantime

**Comment by fheidrich** [comment]
Same problem, please help.

livereload works nicely with taco kit 3 (cordova cli 5.4.1), the second I updated to 6.2.0 it stopped working.

Note that livereload is the main reason for me to use TACO

**Comment by panarasi** [comment]
@fheidrich The live reload functionality is now a part of VSCode. We also have good browser based workflow. Would that work for you ?

**Comment by fheidrich** [comment]
I use VSCode so I'd like to give it shot.  That said, I have a weird setup:
I have JS6 code in a /src folder, I have gulp process that watches /src and uses babel to transpiles JS5 to /www
I have second process (like TACO or cdvlive) that watches from /www and updates /platform/ios/www (traditional cordova reload).

Does VSCode expects me to edit the files inside /www ? Cause I edit the files /src (and babel watches the outputs to /www)

Anyway, is there smarter way to use JS2015 + Cordova ?
I considered using a cordova hooks to intercept when the build is about to copy a file from /www into /platform/ios/www but it quickly became complicated...

**Comment by MSLaguana** [comment]
vscode-cordova, when running in simulation mode using cordova-simulate, should pick up any changes that happen in `/www` (either because you directly modify them, or you have some watcher elsewhere that outputs to there) and reflect them in the running app.

**Comment by fheidrich** [comment]
Thanks, plugin is not happy right now, Cordova Prepare outputs:

########### EXECUTING: cordova prepare ###########
/bin/sh: cordova: command not found
########### FINISHED EXECUTING : cordova prepare ###########

I have cordova in, $which cordova
/Users/fheidric/.nvm/versions/node/v4.3.2/bin/cordova

Is that bad vibe between VSCode and NVM ?
How can I add to the PATH used by VSCode to look for binaries ?
Cheers!

**Comment by MSLaguana** [comment]
How are you launching vscode? I believe that NVM modifies your PATH when you select a version, and so if you started vscode before selecting a node version (or via a GUI when NVM modifies your PATH in a shell startup script) then it will not have the right PATH.

Have you tried opening vscode from the same console you do your node work in? If that doesn't solve it, please open an issue at https://github.com/microsoft/vscode-cordova

**Comment by csantanapr** [comment]
Why was this issue close @MSLaguana?

**Comment by MSLaguana** [comment]
Primarily because we have deprecated taco-cli, and don't want people to have hopes that we would maintain it further. We now recommend that people use something like our vscode extension for livereload.

**Comment by csantanapr** [comment]
Sure I totally understand,
VSCode Rocks !!!!
