### ISSUE TITLE
before_build and after_build hooks are not fired when using remotebuild

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/TACO#272]
At some point in the past the way that Cordova works with hooks has changed, and the approach we had taken to simulate a build via manually triggering before/after_build no longer works.

It looks like Cordova now has the notion of a HooksRunner which deals with all the hooks, however it isn't exposed in cordova-lib and I'm not sure that we should reach into Cordova internals at the moment to play around with it.

**Comment by omefire** [comment]
calling the 'build' function exposed by cordova-lib doesn't work in this case ?

**Comment by MSLaguana** [comment]
We have some steps that we do between "prepare" and "compile": In particular the way that we handle `/res/native/ios/` overrides currently is to call prepare, wait for that to finish, and then go poke around in `/platforms/ios/` to replace the relevant files.

If we can dynamically add an after_prepare hook then we can probably use `cordova build`, but we won't have the same ordering guarantees that we have at the moment.

**Comment by omefire** [comment]
Would it be possible to have some 'global variable' accessible from before_build, after_prepare & before_build hooks ?
Could that be used as a workaround ? 
It's dirty, I know, :(

**Comment by MSLaguana** [comment]
We actually fixed this, hooray!
