### ISSUE TITLE
Live Reload Issue and Comments

### ISSUE THREAD

**Issue by kevinclarkra** [Microsoft/TACO#274]
I tried sending an email to the email on the TACO website but I got this:

Your message to hexauthdev@microsoft.com couldn't be delivered.
The group hexauthdev only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

So posting here

I really like what you have done here with TACO. I got the tools and have been messing around. To be fair, I also have VS 2015 with Cordova and was already debugging in Ripple and on the device before I got the TACO CLI but I like how the CLI adds a livereload option so I don't have to continue rebuilding.

However, I can't get it to work on my device, it just stays on the "Waiting for livereload server" white screen. When I change any file I see :

rm: could not remove directory (code ENOTEMPTY): C:

ms\android\assets\www

mkdir: path already exists: C:\Users\Kevin\testTaco

cp: copyFileSync: could not write to dest file (cod

aco\platforms\android\assets\www\index.html

- An error occurred: Error: EPERM: operation not p

n\testTaco\platforms\android\assets\www\index.html'

When I test on the AVD Emulator, or in the browser, livereload works fine.  Any ideas?

Also, I would love to use Azure Mobile Services, but I don't like how they changed the pricing and stuff.  It's too complicated to understand and I get concerned about no fixed pricing.  https://azure.microsoft.com/en-us/pricing/details/app-service/.  I'm just doing app development on the side, I just want a fixed price, like I could pay Firebase $49 for unlimited apps, unlimited users, and a good amount of data transfer.  Simple, plus has the benefit of being realtime.  But, they don't have things like Push Notifications.

  I will probably end up using Telerik, or Firebase/Ionic, or my own Meteor backend with some service for push notifications.  Every one has slight limitations, for example Telerik's backend isn't realtime like Firebase, although they offer everything else, from a cloud based editor to packaging and deploying to app stores.  Perhaps the best solution is Firebase with Telerik.

In addition, the tutorials I've read on Mobile Services haven't been quite enough COMPLETE to decide to use them over these other options.  I am a capable developer, but I like step by step with lots of screenshots when learning new things.  Ionic and Firebase documentation is excellent and is probably part of the reason for user adoption.

Also, when I go here: https://azure.microsoft.com/en-us/documentation/services/mobile-services/, there is no tutorial for hybrid apps for some things.  For example offline sync, there is no Javascript option, just Native and Xamarin.  With push notifications to Authenticated users, there is only examples for ioS and Windows 8, but not Android.  This link is broken: https://azure.microsoft.com/en-us/documentation/articles/mobile-services-dotnet-backend-use-non-relational-data-store/.

This is C#, not JavaScript: http://giventocode.com/how-to-use-azure-documentdb-with-azure-mobile-services#.Vtj5CfkrLAX.   It's also an independent blog, not even Microsoft's. You compare this article to this one: https://www.firebase.com/docs/web/guide/saving-data.html and tell me which is easier to follow.  I've been doing MS development for a while and always felt that tools are great but documentation is the worst, but luckily there are a lot of books out there to pick up.

Or if there was a good step by step tutorial with using Azure API service with a mobile app, that would be neat too.

I really find hybrid development to be a fun hobby (for now) and I really like how Microsoft is supporting things.  I just wanted to provide some feedback so hopefully can improve Mobile Services as well as documentation.

(Actually, going back to documentation, the TACO blog on livereload was JUST BARELY enough to understand getting it working, I would like just a little more "meat")

Thanks,

Kevin

**Comment by kevinclarkra** [comment]
https://azure.microsoft.com/en-us/pricing/details/mobile-services/ Like this pricing is so much easier to follow for a hobbyist sort of developer.  I think they should keep this pricing for basic apps and use the App Service for more enterprise level applications.  If these mobile services weren't being replaced and there was good documentation on how to use all the features with hybrid apps, I would definitely choose Microsoft for the back end.

**Comment by kevinclarkra** [comment]
Take that back.  The live reload crashes after every change I make.  Same error in the CLI:

rm: could not remove directory (code ENOTEMPTY): C:

ms\android\assets\www

mkdir: path already exists: C:\Users\Kevin\testTaco

cp: copyFileSync: could not write to dest file (cod

aco\platforms\android\assets\www\index.html

An error occurred: Error: EPERM: operation not p
n\testTaco\platforms\android\assets\www\index.html'

Even running the emulator and trying to do debugging in the browser.

Is there anything like ionic serve?  Where it just does debugging in the browser?  And has live reload?

Thanks,

Kevin

**Comment by Shizen** [comment]
Just adding that with just the baseline vanilla app, I get this same error with `taco emulate android --livereload` after the first modification (i.e. the first modification works, but no further modifications).  This with just trivial modifications to `www/index.html`.  I've reproduced this several times so far.

**Comment by MSLaguana** [comment]
We have deprecated taco cli, and suggest using our [vscode extension](https://marketplace.visualstudio.com/items?itemName=vsmobile.cordova-tools) for livereload, using either ionic or cordova-simulate.
