### ISSUE TITLE
taco run ios launches simulator, not device

### ISSUE THREAD

**Issue by SimpleDeveloper49** [Microsoft/TACO#275]
Taco v.1.2.0, iOS 8.+ & iOS 9.2.1, Taco kit 3.0.0.

Using command line: "taco run ios" (optional: --livereload), taco will start the simulator. Reading in the documentation, it hints that this is the fallback if no device is plugged in. 

Device is plugged in. Tried numerous devices, different iOS versions. Works correctly using Visual Studio Codes Cordova Tools. Also works correctly using Xcode.

Thoughts/Suggestions?

**Comment by MSLaguana** [comment]
You can force it to target a device if you pass `--device`. I believe that the default behavior differs between android and ios, but it should match the behavior of the equivalent cordova command. For iOS I believe it always uses the simulator unless you explicitly ask for a --device build.

**Comment by SimpleDeveloper49** [comment]
Thank you @MSLaguana , I must have missed that.

For completion:
1. As advised `taco run ios --device --livereload`
2. Error, regarding ios-deploy not being installed
3. `npm install -g ios-deploy`
4. Works
