### ISSUE TITLE
Livereload error on file change

### ISSUE THREAD

**Issue by jeroengijsman** [Microsoft/TACO#282]
We are running a setup where a babel watch is compiling our react code to a bundle.js in het www/scripts folder. For debugging we want to use sourcemaps. Babel can automatically create sourcemaps and adds it in the same folder as the javascript file. 
Initial startup is fine, as soon as we edit some files and babel changes the sourcemap the following error occurs:

```
[BS] File changed: /Users/jeroen/projects//app/www/scripts/bundle.js.map
 - An error occurred: Error: ENOENT: no such file or directory, open '/Users/jeroen/projects/app/platforms/ios/www/index.html'
```

Any ideas on how to fix this?

**Comment by sushruth** [comment]
I had the same issue when I had turned on "auto save changes" in my code editor. Turning it off helped me get rid of this error. Hope this helps.
