### ISSUE TITLE
Live reload IP selection

### ISSUE THREAD

**Issue by sushruth** [Microsoft/TACO#283]
This is a feature request.

Please provide a CLI way to specify live reload IP address. Maybe something like 

```
taco run android --device --livereload --host=192.168.1.1
```

for example.

This may help people working with multiple networks.

**Comment by sushruth** [comment]
Can anyone please support this if you think this is a nice feature to have ?

**Comment by davidbonting** [comment]
Hi sushruth,
I'm also looking forward to such feature. I managed to do the same manually:

1. **go to** (on windows) (if you have taco installed in default folder)
C:\Users\David\AppData\Roaming\npm\node_modules\taco-cli\node_modules\taco-livereload\lib\livereload.js

2. **within**
var bs = new BrowserSyncServer(projectRoot, {
**beneath**
ghostMode: options.ghostMode || true
**add** (don't forget to add a "," to the one above)
host: "[your ip]"

I hope this works for you!
David
