### ISSUE TITLE
how to make .app file for OS X using taco CLI of Cordova project.

### ISSUE THREAD

**Issue by mohitintelli** [Microsoft/TACO#285]
My issue is that I need to make build cordova project using taco CLI command. I need .APP file for OSX. Please let me know what is wright way.

Thanks

**Comment by joshuaskelton** [comment]
OSX is a valid platform for Cordova, so the below will work:

- `taco platform add osx`
- `taco run osx`

**Note:** This must be done on OSX

**Comment by mohitintelli** [comment]
Thanks for reply,
Sorry I forget to mention that I don't need to execute Taco command on OS-X machine. My problem is that I need to execute taco command on Windows Machine. I want to make build remotly for os-x using windows system. I hope now you are understanding my issue. Please help and if you have any question please ask.

**Comment by MSLaguana** [comment]
Right now we only support building iOS remotely, not OSX. However if you want to build for iOS remotely you still need a mac which can do the build for you; if you have such a machine then you can use it to build for OSX instead of using remotebuild on it.

**Comment by mohitintelli** [comment]
I have mac machine and I have no issue with iOS. I am able to build remotely using windows. But I want same as OSX. If it is possible please provide me solution. Thanks

**Comment by MSLaguana** [comment]
It is not possible at the moment without code changes I'm afraid.

If you are willing to investigate and make the changes yourself, you can either checkout and build from this repo, or go to `~/.taco_home/node_modules/taco-remote-lib/<latest>/node_modules/taco-remote-lib` on the mac and find the compiled equivalent of https://github.com/Microsoft/TACO/tree/master/src/taco-remote-lib there. You would need to make something equivalent to the ios folder, but specialized for building OSX instead (I do not know if any workarounds are required, or what the output it produces looks like). You would then need to add an equivalent to https://github.com/Microsoft/TACO/blob/master/src/taco-remote-lib/tacoRemoteLib.ts#L46 to hook in the new code.

Right now I don't believe that adding OSX support is on our roadmap, but @jmatthiesen may have some input there.
