### ISSUE TITLE
Typo in CheckSettingsForInfo Resource

### ISSUE THREAD

**Issue by Programmerman1** [Microsoft/TACO#286]
Every time you launch remotebuild, it tells you that you can look at the config file in your user directory to see how the server is set up. The only problem is there's a typo telling you that "You many need to run 'remotebuild saveconfig' to generate it." That "many" should be "may."

The typo is in src/remotebuild/resources/en/resources.json on line 42.

**Comment by hamiltonia** [comment]
Thanks for the feedback - we'll get this taken care of with the next release.
