### ISSUE TITLE
Gulp dependencies

### ISSUE THREAD

**Issue by akofman** [Microsoft/TACO#288]
It looks like gulp and gulp-typescript are needed to install taco-cli. Would be nice to add them as dependencies and not devDependencies in package.json. What do you think ?

**Comment by MSLaguana** [comment]
Gulp and gulp-typescript should only be required for compiling taco-cli from sources, not when installing from npm. Why do you suggest adding them to dependencies rather than devDependencies?

**Comment by akofman** [comment]
I agree with you but now if you install taco-cli from npm and you don't have gulp in your project it ends with an error : 
`Error: Cannot find module 'gulp'`

**Comment by akofman** [comment]
It looks like you have a postInstall script which use gulp actually.

**Comment by MSLaguana** [comment]
Our repository as a whole has that postinstall script, but that is never published to npm. The taco-cli package itself uses this package.json https://github.com/Microsoft/TACO/blob/master/src/taco-cli/package.json which just points to this file https://github.com/Microsoft/TACO/blob/master/src/taco-cli/cli/logo.ts which has no dependency on gulp.

If you are getting issues when you `npm install taco-cli`, could you please include your console output here?

**Comment by akofman** [comment]
Yep I'm installing taco-cli from a github url configured in my `package.json` in order to have the last fixes. I think it's a quite common practice so it would be better to get the same behaviour when downloading from the npm repo or from github but it's my personal opinion and I can understand if you don't accept it.

**Comment by MSLaguana** [comment]
Unfortunately we don't support that at all; because this repo actually contains ~7 interconnected projects, you can't install one without compiling the others, so installing directly from this git repo does not work. You'll either have to clone this repo and follow the steps to build manually, or depend on the packages published to npm.

**Comment by akofman** [comment]
Too bad, that's why I suggested to add Gulp as a dependency ;)
What about publishing the last versions on npm ? I can see the last version is 1.4.0 on github and 1.2.0 on npm (assuming you're using the same versioning way).

**Comment by MSLaguana** [comment]
Version numbers are another casualty of this monorepo we have here: The last published version of taco-cli is still 1.2.0 as specified in https://github.com/Microsoft/TACO/blob/master/src/taco-cli/package.json, but the "version 1.4.0" that was published today is kind of a "repo version". We published new versions of taco-remote-lib and taco-utils yesterday, and so I updated the tag so we can find this wave of releases in future if need be, but that "1.4.0" is purely imaginary.

**Comment by akofman** [comment]
Haha ok good to know. Thanks for your feedback.
