### ISSUE TITLE
Livereload error after TypeScript pre-compilation is performed

### ISSUE THREAD

**Issue by jdrm** [Microsoft/TACO#289]
Creating a new project with TypeScript template and add the iOS platform:

```
taco create helloWorld --template typescript
taco platform add ios
```

Invoke gulp for ts pre compilation:

`gulp`

Then run with livereload:

`taco emulate ios --livereload
`

It loads and displays just fine but as soon as I change anything in the index.ts file and invoke pre compilation again:

`gulp`

Then I get this error and livereload stops working:
```
[BS] File changed: /Users/jdrm/dev/helloWorld/www/scripts/index.js
 - An error occurred: Error: ENOENT: no such file or directory, open '/Users/jdrm/dev/helloWorld/platforms/ios/www/index.html'
```

**Comment by MSLaguana** [comment]
We are deprecating taco and suggest using our [vscode extension](https://marketplace.visualstudio.com/items?itemName=vsmobile.cordova-tools) for live reload, with either ionic or cordova-simulate.
