### ISSUE TITLE
Remotebuild does not respond after "Saving build request payload"

### ISSUE THREAD

**Issue by sudarsanyes** [Microsoft/TACO#291]
I am using Visual Studio 2015 running in Windows 7 + remotebuild running on a MacMini to test my Cordova apps in an iOS Simulator. I was able to build, deploy and test my app successfully until today. 

Recently, whenever I compile for iOS, the compilation fails. 
Here is a trace of where it fails. 

```
iosdevs-Mac-mini:~ foo$ remotebuild
Warning: No server modules selected. Defaulting to configuration "modules": {"taco-remote": { "mountPath": "cordova"} }
Remote build server listening on [https] port 3000
Please view/edit server configuration at /Users/foo/.taco_home/RemoteBuild.config. You many need to run 'remotebuild saveconfig' to generate it. You will have to restart the server if you update the server configurations.
GET /certs/369410 200 20.499 ms - 4278
GET /modules/taco-remote 200 4.417 ms - 7
New build request submitted:
/build/tasks?command=build&vcordova=6.0.0&cfg=debug&loglevel=warn
{"accept-language":"en-US","host":"10.208.166.171:3000","connection":"close","transfer-encoding":"chunked"}

Downloading: taco-remote-multiplexer
taco-remote-multiplexer@1.2.8 .taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer
└── semver@4.3.4

taco-remote-multiplexer downloaded and installed.
Build will be executed under: /Users/foo/.taco_home/remote-builds/taco-remote/builds/1668
Saving build request payload to : /Users/foo/.taco_home/remote-builds/taco-remote/builds/1668
POST /cordova/build/tasks?command=build&vcordova=6.0.0&cfg=debug&loglevel=warn - - ms - -
```

Ideally after "Saving build request..." I should be able to see "Saved build request..." followed by "Extracting..." but from today morning this does not happen. Instead, Visual Studio will timeout and throw an error stating that it cannot reach the build server. 

The following are some of the solutions that I tried, but in vain. 
1. Restarted remotebuild. 
2. Restarted OSX. 
3. Restarted Visual Studio. 
4. Restarted Windows. 
5. Reset certificates. 
6. Manually deleted builds folder from /Users/foo/.taco_home/remote-builds/taco-remote/
7. Delete the platforms/ios folder and then rebuild using Visual Studio.  

_My observations
I noticed that the tgz file under the build couldn't be extracted. When I tried extracting it, it throws an error which kind of indicates that the package is broken(!?). But if I copy the xcode project from playforms/ios folder (generated during the build) manually to my OSX and then open+run it using xcode, it seems to work just fine!_

**Comment by sudarsanyes** [comment]
Here is the trace from Visual Studio. 

```
1>------ Build started: Project: Panda.Cordova, Configuration: Debug iOS ------
1>  Your environment has been set up for using Node.js 0.12.2 (ia32) and npm.
1>  ------ Ensuring correct global installation of package from source package directory: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\APACHECORDOVATOOLS\packages\vs-tac
1>  ------ Name from source package.json: vs-tac
1>  ------ Version from source package.json: 1.0.37
1>  ------ Package already installed globally at correct version.
1>  ------ Cordova tools 6.0.0 already installed.
1>  ------ Build Settings:
1>  ------ Build Settings:
1>  ------    platformConfigurationBldDir: C:\Users\foo\Documents\Visual Studio 2015\Projects\Cordova\Panda.Cordova\Panda.Cordova\bld\iOS\Debug
1>  ------    platformConfigurationBinDir: C:\Users\foo\Documents\Visual Studio 2015\Projects\Cordova\Panda.Cordova\Panda.Cordova\bin\iOS\Debug
1>  ------    buildCommand: build
1>  ------    platform: iOS
1>  ------    cordovaPlatform: ios
1>  ------    configuration: Debug
1>  ------    cordovaConfiguration: Debug
1>  ------    projectName: Panda.Cordova
1>  ------    projectSourceDir: C:\Users\foo\Documents\Visual Studio 2015\Projects\Cordova\Panda.Cordova\Panda.Cordova
1>  ------    npmInstallDir: C:\Users\foo\AppData\Roaming\npm
1>  ------    buildServerUrl: https://10.208.166.171:3000/cordova
1>  ------    buildTarget: iOSEmulatoriPhone5S
1>  ------    language: en-US
1>  ------ Platform ios already exists
1>  ------ Updating plugins
1>  ------ Currently installed plugins: cordova-plugin-console@1.0.2,cordova-plugin-device@1.1.1,cordova-plugin-statusbar@2.1.2,cordova-plugin-whitelist@1.2.1,ionic-plugin-keyboard@1.0.9
1>  ------ Currently installed dependent plugins:
1>  ------ Currently configured plugins:
1>  ------ Incremental Build: false
1>  ------ Submitting new build request to: https://10.208.166.171:3000/cordova/build/tasks?command=build&vcordova=6.0.0&cfg=debug&loglevel=warn
1>MSBUILD : cordova-build error : Error: Secure connection to https://10.208.166.171:3000/cordova could not be established. Verify that the build server is running in secure mode.
1>  Error Secure connection to https://10.208.166.171:3000/cordova could not be established. Verify that the build server is running in secure mode.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

I also tried changing the port number and turning On and Off the secure channel (--secure false), but in vain!

**Comment by MSLaguana** [comment]
When was the last time you successfully built a project using remotebuild, and had you changed anything since then? I haven't seen this error, but I haven't tried using windows 7 recently.

The error you are getting about secure builds is likely caused by you resetting certificates; you will need to either disable secure mode on both ends, or re-enter a new PIN to set up a new secure connection.

Once you get VS talking to remotebuild again, if the issue with extracting the tgz persists could you please also try and see if this affects a freshly created project, or if it is only your project which causes the issue.

**Comment by MSLaguana** [comment]
Also, the lack of "Build uploaded successfully" indicates that the tarball was not completely uploaded. There may have been a network issue which interrupted the upload potentially, but if that is the case then retrying should have worked (unless your network is in a very bad state)

**Comment by sudarsanyes** [comment]
@MSLaguana i was able to build yesterday and i did not change my environment since then. 
here are some more information for you...
1. i tried resetting certificates => didn't work. 
2. i tried turning off secure mode at both the ends => didn't work either. 
3. i tired switching to different n/w all together => didn't work. 

really strange!

**Comment by sudarsanyes** [comment]
@MSLaguana does visual studio (remotebuild in Windows) use zlib to create the tarball?

**Comment by MSLaguana** [comment]
How are you trying to connect to the mac? by hostname, or ip address? And what happens if you try to connect to `http://<mac>:3000/` in a browser from your windows PC (replacing port if you are using a non-standard port)? You should get a page saying `Remote build Express server open for business on port 3000`.

It's been a little while since I looked at how VS packages things up, but I do believe it uses zlib bundled with nodejs to create the tarball.

Something else you could try: See if you can use `taco-cli` to communicate with your server. You just need to `npm install -g taco-cli`, then `taco remote add ios`, follow the prompts, and then inside your project root do `taco build ios --remote`. I'm more familiar with the taco-cli code paths so that can help troubleshoot where things are failing.

**Comment by sudarsanyes** [comment]
@MSLaguana 
1. I connect to my mac using ip address. 
2. If I use my browser and browse to http://<mac>:3000/, I see "Remote build Express server open for business on port 3000".

**Comment by sudarsanyes** [comment]
@MSLaguana it works now! 
In my windows, I opened command prompt and tried executing `npm update -g zlib` and `npm update -g tar` and now my OSX is able to complete the build pipe. 

could this (update zlib/tar) have fixed the issue?

**Comment by MSLaguana** [comment]
I would not expect so, since global installs of node packages do not usually get picked up by local installs of packages, and vs-tac (the npm package used by VS to build cordova projects) is installed locally somewhere. I suspect that it was a transient network issue, but it's hard to tell. Glad to hear that things are working for you again though!

**Comment by sudarsanyes** [comment]
@MSLaguana  now back to square 1 - things have stopped working once again! :(
seems to be really strange...

**Comment by MSLaguana** [comment]
Can you please include the end of the "output" window in VS from when this last failed? And when it does fail, please try to connect to `http://<mac>:3000` to ensure that you have connectivity.

**Comment by sudarsanyes** [comment]
```
1>------ Build started: Project: Panda.Cordova, Configuration: Debug iOS ------
1>  Your environment has been set up for using Node.js 0.12.2 (ia32) and npm.
1>  ------ Ensuring correct global installation of package from source package directory: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\APACHECORDOVATOOLS\packages\vs-tac
1>  ------ Name from source package.json: vs-tac
1>  ------ Version from source package.json: 1.0.37
1>  ------ Package already installed globally at correct version.
1>  ------ Cordova tools 6.0.0 already installed.
1>  ------ Build Settings:
1>  ------ Build Settings:
1>  ------    platformConfigurationBldDir: C:\Users\sesa151027.APA\Documents\Visual Studio 2015\Projects\Cordova\Panda.Cordova\Panda.Cordova\bld\iOS\Debug
1>  ------    platformConfigurationBinDir: C:\Users\sesa151027.APA\Documents\Visual Studio 2015\Projects\Cordova\Panda.Cordova\Panda.Cordova\bin\iOS\Debug
1>  ------    buildCommand: build
1>  ------    platform: iOS
1>  ------    cordovaPlatform: ios
1>  ------    configuration: Debug
1>  ------    cordovaConfiguration: Debug
1>  ------    projectName: Panda.Cordova
1>  ------    projectSourceDir: C:\Users\sesa151027.APA\Documents\Visual Studio 2015\Projects\Cordova\Panda.Cordova\Panda.Cordova
1>  ------    npmInstallDir: C:\Users\sesa151027.APA\AppData\Roaming\npm
1>  ------    buildServerUrl: https://10.208.166.171:3000/cordova
1>  ------    buildTarget: iOSEmulatoriPhone5S
1>  ------    language: en-US
1>  ------ Platform ios already exists
1>  ------ Updating plugins
1>  ------ Currently installed plugins: cordova-plugin-console@1.0.2,cordova-plugin-device@1.1.1,cordova-plugin-statusbar@2.1.2,cordova-plugin-whitelist@1.2.1,ionic-plugin-keyboard@1.0.9
1>  ------ Currently installed dependent plugins:
1>  ------ Currently configured plugins:
1>  ------ Incremental Build: false
1>  ------ Submitting new build request to: https://10.208.166.171:3000/cordova/build/tasks?command=build&vcordova=6.0.0&cfg=debug&loglevel=warn
1>MSBUILD : cordova-build error : Error: Secure connection to https://10.208.166.171:3000/cordova could not be established. Verify that the build server is running in secure mode.
1>  Error Secure connection to https://10.208.166.171:3000/cordova could not be established. Verify that the build server is running in secure mode.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

```

and this is what i see in the browser, 

`Remote build Express server open for business on port 3000
`

**Comment by MSLaguana** [comment]
Have you reconfigured either VS or the remote server? It looks to me like VS is attempting to connect to the remote server in secure mode, but remotebuild may be in insecure mode.

**Comment by sudarsanyes** [comment]
@MSLaguana no. remote server is in secure mode. this is the remote server trace. 

```
iosdevs-Mac-mini:~ sudarsan.srinivasan.se$ remotebuild
Warning: No server modules selected. Defaulting to configuration "modules": {"taco-remote": { "mountPath": "cordova"} }
Remote build server listening on [https] port 3000
Please view/edit server configuration at /Users/sudarsan.srinivasan.se/.taco_home/RemoteBuild.config. You many need to run 'remotebuild saveconfig' to generate it. You will have to restart the server if you update the server configurations.
New build request submitted:
/build/tasks?command=build&vcordova=6.0.0&cfg=debug&loglevel=warn
{"accept-language":"en-US","host":"10.208.166.171:3000","connection":"close","transfer-encoding":"chunked"}
Build will be executed under: /Users/sudarsan.srinivasan.se/.taco_home/remote-builds/taco-remote/builds/2134
Saving build request payload to : /Users/sudarsan.srinivasan.se/.taco_home/remote-builds/taco-remote/builds/2134
POST /cordova/build/tasks?command=build&vcordova=6.0.0&cfg=debug&loglevel=warn - - ms - -
GET / 200 10.179 ms - 58
GET /favicon.ico 404 4.664 ms - 24
```

**Comment by MSLaguana** [comment]
One other possibility comes to mind: Have you changed networks / IP addresses? Try `remotebuild certificates reset` to create new certificates with your current IP address, and re-pair with VS. The list of acceptable IP addresses is finalised at certificate creation time, so if you are changing wifi etc, that can mess things up.

**Comment by sudarsanyes** [comment]
i tried doing `remotebuild certificates reset ` and it does not seem to solve the issue.

**Comment by MSLaguana** [comment]
I'm not sure what the underlying issue is then; Could you please try my earlier suggestion of using `taco-cli`? You should be able to just `npm install -g taco-cli; taco remote add ios`, fill out the relevant details, then in the project root run `taco build ios --remote`. If that fails, it may give some more insight into what is happening.

**Comment by sudarsanyes** [comment]
I tried following `taco build ios --remote` and it fails the same way. 

```
C:\Users\sesa151027.APA\Documents\Visual Studio 2015\Projects\Cordova\Panda.Cordova>taco remote add ios
Please ensure that remotebuild is running on the remote server.
 You can generate new client information at any time by typing 'remotebuild certificates generate'. For more details, see http://go.microsoft.com/fwlink/?LinkId=624345
Remote host name / IP address: 10.208.166.171
Port number: 3000
PIN (leave blank for insecure servers): 570151
Success! Settings stored in C:\Users\sesa151027.APA\AppData\Roaming\taco_home\TacoSettings.json

Quick tips & commands:
 * Build your app: taco build <PLATFORM>
 * Run your app in the emulator: taco emulate <PLATFORM>
 * Run your app on a device: taco run <PLATFORM>

For command help, use 'taco help'
For full documentation online, use 'taco docs'


C:\Users\sesa151027.APA\Documents\Visual Studio 2015\Projects\Cordova\Panda.Cordova>taco build ios --remote
------ Incremental Build: false
------ Submitting new build request to: https://10.208.166.171:3000/cordova/build/tasks?command=build&vcordova=6.1.1&vcli=1.2.1&cfg=debug&platform=ios
TACO5629: Remote build failed
Inner Error:
Secure connection to https://10.208.166.171:3000/cordova could not be established. Verify that the build server is running in secure mode.

C:\Users\sesa151027.APA\Documents\Visual Studio 2015\Projects\Cordova\Panda.Cordova>
```

**Comment by MSLaguana** [comment]
I'll have to take a closer look tomorrow. What confuses me is that in `taco-cli` we definitely do a secure https connection when you do `taco remote add ios`, so the connection works, but it fails when you build. The specific failure is an `ECONNRESET`, which I've typically seen when you try to do a httpS connection to a server running in non-secure http mode.

Does this failure happen quickly for you, or only after some time? I still wonder whether there is something to do with your network connection; the shorter lived connections made earlier on might survive while a longer-lived upload (especially if your project is a bit large?) might get disrupted.

**Comment by MSLaguana** [comment]
If you get a chance, you could also try building a clean project, either via VS or `taco create newProject; cd newProject; taco build ios --remote` and see if that has an impact.

**Comment by sudarsanyes** [comment]
@MSLaguana the failure takes some time, it does not happen quickly! it takes around 3 minutes for the  error message to popup after "saving..." trace message. 
by the way, my project is an ionic project and contains around 4 views. 2 controllers. previously uploaded (successful) **tarball packages measured around 3 MB**.

**Comment by sudarsanyes** [comment]
@MSLaguana i modified the file `C:\Users\sesa151027.APA\AppData\Roaming\npm\node_modules\taco-cli\cli\remoteBuild\remoteBuildClientHelper.js ln: 219`. instead of returning a localized string, I returned the `requestError `object itself and this is how the trace looked like. 

```
C:\Users\sesa151027.APA\Documents\Visual Studio 2015\Projects\Cordova\Panda.Cordova>taco build ios --remote
------ Incremental Build: false
------ Submitting new build request to: https://10.208.166.171:3000/cordova/build/tasks?command=build&vcordova=6.1.1&vcli=1.2.1&cfg=debug&platform=ios
TACO5629: Remote build failed
Inner Error:
socket hang up
```

**Comment by MSLaguana** [comment]
Do you know what proxy you are using? I haven't tested extensively with proxies, but if the proxy is dropping the connection after a few minutes, that would cause this issue. If you can let me know what kind of proxy / how it is configured, I'll see if I can replicate the issue.

**Comment by sudarsanyes** [comment]
@MSLaguana 

```
C:\Users\sesa151027.APA>npm config list
; cli configs
user-agent = "npm/2.7.4 node/v0.12.2 win32 ia32"

; userconfig C:\Users\sesa151027.APA\.npmrc
https-proxy = "http://103.27.171.32:80/"
prefix = "C:\\Users\\sesa151027.APA\\AppData\\Roaming\\npm"
proxy = "http://103.27.171.32:80/"

; builtin config undefined
prefix = "C:\\Users\\sesa151027.APA\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files (x86)\nodejs\\node.exe
; cwd = C:\Users\sesa151027.APA
; HOME = C:\Users\sesa151027.APA
; 'npm config ls -l' to show all defaults.


C:\Users\sesa151027.APA>
```

**Comment by MSLaguana** [comment]
I was hoping for the software that the proxy is running, do you happen to know that?

**Comment by sudarsanyes** [comment]
@MSLaguana no idea. i am on a corporate n/w. 
by the way, any idea why i got **socket hang up**? some time out or stream length issue?

**Comment by MSLaguana** [comment]
That's what I'm trying to work out. There's nothing in VS or remotebuild to stop the upload after a timeout, but the proxy may be causing that to happen.

**Comment by MSLaguana** [comment]
@sudarsanyes: I've just read about an issue which sounds similar to what you encountered here at https://blog.cloudflare.com/the-curious-case-of-slow-downloads/

It suggests that there may be a workaround, if this is in fact the same issue. Could you please try the following: Go to wherever you have installed remotebuild (likely something like `/usr/lib/node_modules/remotebuild`) and then find `lib/server.js`. In that file, look for two instances of `svr.listen(...`. Just before each of them, add `svr.setTimeout(5 * 60 * 1000);;` to change the timeout for inactive connections. If that fixes the issue, please let me know and I'll work on a proper fix.

**Comment by ibnbd** [comment]
Same issue :( any solutions?


```
1>------ Build started: Project: retail.email, Configuration: Debug iOS ------
1>  ------ Ensuring correct global installation of package from source package directory: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\ApacheCordovaTools\packages\vs-tac
1>  ------ Name from source package.json: vs-tac
1>  ------ Version from source package.json: 1.0.42
1>  ------ Package already installed globally at correct version.
1>  ------ Cordova tools 6.1.1 already installed.
1>  ------ Build Settings:
1>  ------ Build Settings:
1>  ------    platformConfigurationBldDir: C:\Users\ahsta\Dropbox\retail.email\app\retail.email\bld\iOS\Debug
1>  ------    platformConfigurationBinDir: C:\Users\ahsta\Dropbox\retail.email\app\retail.email\bin\iOS\Debug
1>  ------    buildCommand: build
1>  ------    platform: iOS
1>  ------    cordovaPlatform: ios
1>  ------    configuration: Debug
1>  ------    cordovaConfiguration: Debug
1>  ------    projectName: retail.email
1>  ------    projectSourceDir: C:\Users\ahsta\Dropbox\retail.email\app\retail.email
1>  ------    npmInstallDir: C:\Users\ahsta\AppData\Roaming\npm
1>  ------    buildServerUrl: https://192.168.1.5:3000/cordova
1>  ------    buildTarget: iOSEmulatoriPhone6
1>  ------    language: en-US
1>  ------ Platform ios already exists
1>  ------ Updating plugins
1>  ------ Currently installed plugins: cordova-plugin-app-event@1.2.0,cordova-plugin-background-mode@0.6.5,cordova-plugin-badge@0.7.2,cordova-plugin-compat@1.0.0,cordova-plugin-console@1.0.3,cordova-plugin-device@1.1.2,cordova-plugin-file@4.2.0,cordova-plugin-inappbrowser@1.4.0,cordova-plugin-splashscreen@3.2.2,cordova-plugin-statusbar@2.1.3,cordova-plugin-whitelist@1.2.2,cordova-sqlite-storage@1.4.0,de.appplant.cordova.plugin.local-notification@0.8.4,ionic-plugin-keyboard@2.1.0
1>  ------ Currently installed dependent plugins: cordova-plugin-device,cordova-plugin-app-event,cordova-plugin-compat
1>  ------ Currently configured plugins:
1>  ------ Incremental Build: false
1>  ------ Submitting new build request to: https://192.168.1.5:3000/cordova/build/tasks?command=build&vcordova=6.1.1&cfg=debug&loglevel=warn
1>MSBUILD : cordova-build error : Error: Secure connection to https://192.168.1.5:3000/cordova could not be established. Verify that the build server is running in secure mode.
1>  Error Secure connection to https://192.168.1.5:3000/cordova could not be established. Verify that the build server is running in secure mode.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

```
New build request submitted:
/build/tasks?command=build&vcordova=6.1.1&cfg=debug&loglevel=warn
{"accept-language":"en-US","host":"192.168.1.5:3000","connection":"close","transfer-encoding":"chunked"}
Build will be executed under: /Users/ahstanin/.taco_home/remote-builds/taco-remote/builds/21329
Saving build request payload to : /Users/ahstanin/.taco_home/remote-builds/taco-remote/builds/21329
POST /cordova/build/tasks?command=build&vcordova=6.1.1&cfg=debug&loglevel=warn - - ms - -
```

**Comment by ibnbd** [comment]
Also tried `taco-cli` no luck :(
Tried on two different Macbook (1 with Bootcamp windows). As well tried on a single Macbook using Parallels Desktop.

All three of them return with 
`Error Secure connection to https://192.168.1.5:3000/cordova could not be established. Verify that the build server is running in secure mode.`

Tried with `remotebuild --secure false` and result is
`Error Non-secure connection to http://192.168.1.5:3000/cordova could not be established. Verify that the build server is not running in secure mode.`


Any other copy paste way to build the app? like copy a directory and paste on mac and build with commands or xcode?

Please need help


Thanks

**Comment by ibnbd** [comment]
Tried `remotebuild test`
And request values were 
```
{
  "host": "akrams-macbook-pro.local:3000",
  "connection": "close",
  "transfer-encoding": "chunked"
}
/build/tasks/?vcordova=5.4.0&vcli=1.3.4&cfg=debug&command=build&options=--emulator
/cordova/build/tasks/?vcordova=5.4.0&vcli=1.3.4&cfg=debug&command=build&options=--emulator

```
Which build a test app.

While request from Visual Studio is
```
{
  "accept-language": "en-US",
  "host": "192.168.1.5:3000",
  "connection": "close",
  "transfer-encoding": "chunked"
}

/build/tasks?command=build&vcordova=6.1.1&cfg=debug&loglevel=warn
/cordova/build/tasks?command=build&vcordova=6.1.1&cfg=debug&loglevel=warn
```

Which creating a new directory on `/Users/ahstanin/.taco_home/remote-builds/taco-remote/builds` and uploading a `tgz` file and end with an error

`Error Secure connection to https://192.168.1.5:3000/cordova could not be established. Verify that the build server is running in secure mode.`

Question is how important URL parameter "`command` and `options`" is?
Another question is there any upload limit like PHP?

Thank You

**Comment by ibnbd** [comment]
I tried from a Dedicated Windows PC and it's working perfect, seems like something wrong with my Visual Studio. But I installed same components and settings. Still need a fix for Macbook (Bootcamp/Parallels Desktop), because I don't own a PC.

**Comment by ibnbd** [comment]
I start a new project from sketch, it took me 3 hours to add a file and check on remotebuild. This problem causing by CSS file, my css file seems has some unrecognized property and visual studio (taco) giving this error.

`Error Secure connection to https://192.168.1.5:3000/cordova could not be established. Verify that the build server is running in secure mode.`

Any idea how to fix it?

**Comment by MSLaguana** [comment]
Why do you think it is your CSS file causing issues? When sending the project to the server we do not look at any of the contents, we just upload a tarball and then unpack it.

Is your project that fails to upload large, and does it take several minutes before failing? What exactly are the differences between the cases where it works, and the cases where it doesn't? It sounds like if you try to build from within parallels you run into problems while talking to the same mac from a different windows machine (with the same project?) works?

**Comment by MSLaguana** [comment]
Did you also try the potential workaround I listed above?

**Comment by ibnbd** [comment]
I am very confused, thought it's CSS problem; but not. I checked every single plugin (maybe wrong if use cache version).


So now I tried with my parallels and Macbook, remotebuild on same system. A blank project and it worked perfect. Then I tried to start my project from sketch installed plugin and simulate, I have simulated each time I made a change. When I input css it gave me same error, so I thought CSS causing the problem. I erased the CSS and same problem again.

Yes it takes long time on "Submitting new build" My project working for local Windows + Android build. Means my project has 3 platform.

**Comment by ibnbd** [comment]
My last successful build log https://gist.github.com/ibnbd/9a1ecd0722a573b4f60daca756aa12c5

**Comment by MSLaguana** [comment]
Could you please try the potential workaround I mention in https://github.com/Microsoft/TACO/issues/291#issuecomment-216904786

It may be a timing-related failure, and so adding the one extra css file may have made it just big enough to take enough time uploading that it causes the issue. If the workaround works, then I can work on implementing a proper fix.

**Comment by ibnbd** [comment]
WOW, it worked....... You saved the day brother. I have been working on this since morning. Made me crazy, changed many options on my app. Thank You very much.

Wish you will upload this change on next versions.

**Comment by MSLaguana** [comment]
Thanks for trying that out and letting me know. I'll work on getting the fix in a better format.

**Comment by MSLaguana** [comment]
Once we publish a new version, new installs of remotebuild should no longer have this issue.

**Comment by mrHassanRaza** [comment]
I am using nodeJS and same error occures 

**TACO5629: Remote build failed**
Inner Error:
Remote build error from the build server Build failed with error Failed to fetch plugin cordova-plugin-vs-taco-support via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 254 Error output:
npm WARN checkPermissions Missing write access to /Users/jobeamusa/.taco_home/remote-builds/taco-remote/builds/1735/cordovaApp/node_modules/cordova-admob-sdklibs
npm WARN checkPermissions Missing write access to /Users/jobeamusa/.taco_home/remote-builds/taco-remote/builds/1735/cordovaApp/node_modules/cordova-plugin-whitelist
npm WARN checkPermissions Missing write access to /Users/jobeamusa/.taco_home/remote-builds/taco-remote/builds/1735/cordovaApp/node_modules/polarcape-cordova-plugin-document-handler
npm ERR! path /Users/jobeamusa/.taco_home/remote-builds/taco-remote/builds/1735/cordovaApp/node_modules/cordova-admob-sdklibs
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/Users/jobeamusa/.taco_home/remote-builds/taco-remote/builds/1735/cordovaApp/node_modules/cordova-admob-sdklibs'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by SergTomcat** [comment]
@mrHassanRaza any luck with that?

**Comment by mylertitchell** [comment]
TACO5629: Remote build failed
Inner Error:
Remote build error from the build server Build failed with error Failed to fetch plugin cordova-plugin-vs-taco-support via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 254 Error output:
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-android-permissions
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-bluetoothclassic-serial
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-app-version
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-device
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-dialogs
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-file
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-file-opener2
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-file-transfer
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-geolocation
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-inappbrowser
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-navigationbar
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-network-information
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-screen-orientation
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-statusbar
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-whitelist
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-wkwebview-engine
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-wkwebview-file-xhr
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-sqlite-storage
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/ionic-plugin-keyboard
npm WARN checkPermissions Missing write access to /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/uk.co.workingedge.cordova.plugin.sqliteporter
npm WARN VetIMPRESS@3.0.0 No repository field.

npm ERR! path /Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-android-permissions
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/Users/AppleDev/.taco_home/remote-builds/taco-remote/builds/35939/cordovaApp/node_modules/cordova-plugin-android-permissions'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

getting this error myself, cannot build running cordova 8.1.2, cordovar-android 9.0.0, cordova -ios 6.1 node 11.15 and npm 6.7. To my understanding after ios latest breaking changes this is the highest versions i could currently get working
