### ISSUE TITLE
SignalR connection issue

### ISSUE THREAD

**Issue by christophedemey** [Microsoft/TACO#292]
Hi

Can anyone please help me get signalr working on apache cordova or provide working example.
I have asked the question on stackoverflow and tagged to the taco team 26 days ago.
Am i asking my question in the wrong place ?

Please give some response, there is no info that helps on google :-(

Thanks.

**Comment by MSLaguana** [comment]
What are you actually having trouble with? I don't have personal experience with signalR, but searching for it I found several examples of people discussing how to use it with cordova, including https://blogs.msdn.microsoft.com/cesardelatorre/2014/12/01/myshuttle-biz-and-multi-device-development-of-hybrid-apps-for-ios-android-and-windows-with-visual-studio-tools-for-apache-cordova/ and http://agilefromthegroundup.blogspot.com/2012/09/getting-signalr-and-phonegap-working.html

**Comment by christophedemey** [comment]
Hi MSLaguana, thanks for replying.
I'm sorry i forgot to provide the link of the stackoverflow issue.
https://stackoverflow.com/questions/36518449/apache-cordova-app-in-visual-studio-with-signalr-not-connecting
This also has a link to the github repository where i recreated the problem.
I am also just using the simple chat example.
I am a signalr veteran on the full ASP.NET framework and client side but i cannot find the resolution for this problem.

Thanks.

**Comment by christophedemey** [comment]
Hi

Why was this closed? There was never a solution.
I provided everything i could : Source code, full description of the problem.

Thanks.

**Comment by panarasi** [comment]
@christophedemey Sorry it the reason for closing it was not clear. This repository was dedicated to answer questions about the TACO toolchain itself. Your question sounds more about Apache Cordova and Signalr integration. 

StackOverflow is indeed the right place for that question.

**Comment by christophedemey** [comment]
@panarasi, Ok, at least now i know how muich community support is behind the apache cordova and at this point i dont think it would be wise for me to continue with it.

**Comment by panarasi** [comment]
@christophedemey You can also ping the Cordova community on the slack channel.
