### ISSUE TITLE
livereload does not work with cordova ios 4.1.1

### ISSUE THREAD

**Issue by adamiprinciples** [Microsoft/TACO#295]
Working great with ios 3.9.2, but with the latest(4.1.1) the process just dies after build. It says a log was written, but when you goto the location, nothing is there.

To reproduce easily :

1. Run `taco create myapp`
2. Open config.xml and add `<engine name="ios" spec="4.1.1" />`
3. Run `taco prepare`
4. Run `taco run ios --livereload`

**Comment by adamiprinciples** [comment]
Further testing indicates this doesn't work from 4.0.0 up

**Comment by slorber** [comment]
Hey. From the same subject I'm looking at TACO kits and none of them include ios platform 4.x

Does it mean you estimate this platform is not stable enough?

**Comment by MSLaguana** [comment]
We are deprecating taco, and recommend using our [vscode extension](https://marketplace.visualstudio.com/items?itemName=vsmobile.cordova-tools) for livereload, using either ionic or cordova-simulate.

Newer versions of iOS are fairly stable, but we didn't have the time to produce new sets of kits.
