### ISSUE TITLE
Cordova ios build fails after update to ver 6.0

### ISSUE THREAD

**Issue by Shogun666** [Microsoft/TACO#296]
Hello.

I'm having an issue with remote build on ios. Before everything worked fine.

My error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		
Error: Remote build error from the build server Build failed with error Error code 65 for command: xcodebuild with args: -xcconfig,/Users/marek/.taco_home/remote-builds/taco-remote/builds/716/cordovaApp/platforms/ios/cordova/build-debug.xcconfig,-project,Panel Klienta.xcodeproj,ARCHS=armv7 arm64,-target,Panel Klienta,-configuration,Debug,-sdk,iphoneos,build,VALID_ARCHS=armv7 arm64,CONFIGURATION_BUILD_DIR=/Users/marek/.taco_home/remote-builds/taco-remote/builds/716/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/marek/.taco_home/remote-builds/taco-remote/builds/716/cordovaApp/platforms/ios/build/sharedpch - 1 

I canoot find solution. Installed plugins: InAppBroeser, Whitelist, File, Network Information

Part of output: http://pastebin.com/NvJsze1g
I think answer is there :)

**Comment by MSLaguana** [comment]
If you look at the error log there is an error to do with the inappbrowser plugin. When you updated cordova, you may need to update the plugin as well due to changes in the platform.

**Comment by Shogun666** [comment]
Thanks for answer. I've updated plugins - build fine, but there's another problem. I'm getting 404 error on deploy :/
I have no idea whatsoever why this isn't working...

Image with error: http://postimg.org/image/u1lfzub9t/

Visual Studio Errors:
Severity Code Description Project File Line Suppression State Error: Http 404: Can not find the attached devices; whether it was connected and unlocked?
Severity Code Description Project File Line Suppression State Error: You can not deploy a remote iOS for compiling C: \ ... \ Debug \ buildInfo.json to https://192.168.15.23:3000/cordova:

**Comment by MSLaguana** [comment]
The error that you show there indicates the issue: It can't find an iOS device to deploy to. Do you have a device plugged into the remote mac running the build? Is the device on and unlocked?

**Comment by Shogun666** [comment]
Problem solved. I needed to update osx and xcode to newest versions because of ios 9.3.x on my ipad :)
Thanks for help
