### ISSUE TITLE
Stuck when VS2015 debug using Ripple

### ISSUE THREAD

**Issue by jimior2** [Microsoft/TACO#297]
When I debug on cordova using Ripple will produce those output sometimes, and when this happen it sometimes stuck, any soution on this?

2>  [32mINFO:[39m Server instance running on: [36mhttp://localhost:4400[39m
2>  [32mINFO:[39m CORS XHR proxy service on: [36mhttp://localhost:4400/ripple/xhr_proxy[39m
2>  [32mINFO:[39m JSONP XHR proxy service on: [36mhttp://localhost:4400/ripple/jsonp_xhr_proxy[39m
2>  Cordova 3.0 Project detected...
2>  [32mINFO: [39mCould not find cordova as a local module. Expecting to find it installed globally.

**Comment by MSLaguana** [comment]
This repository is not directly related to the Visual Studio extension, but I can pass this on. What do you mean by "It always stuck"? Are you using the latest update of the Tools for Apache Cordova extension? (Update 9 I believe)

**Comment by jimior2** [comment]
@MSLaguana , sorry not always, I've revised to sometimes, Yes, I update to the lasted 9. but no luck, after many times debug process, and this will happen. Which board I could add a issue for this?

**Comment by TimBarham** [comment]
@jimior2 - that console output looks normal to me. Can you describe what you mean by "stuck"?

**Comment by jimior2** [comment]
@TimBarham "stuck" meaning, when this message in the output window, then Ripple will not startup anymore. I need to close VS2015, and open the solution again. Then I could start to debug.

**Comment by stevefuzzy** [comment]
This is happening to me as well.  You click Run on one of the Ripple options, and it says 'deploying', but it never completes deploying, and the ripple emulator never actually starts up

**Comment by mdczaplicki** [comment]
Happens to me as well

**Comment by VaibhavDhokale** [comment]
Workaround:
Make sure your computer has an internet connection, and
·         If the “Tools for Universal Windows Apps Development” are still installed:
1.       Go to Programs and Features, select Visual Studio 2105, click Change.
2.      In Visual Studio setup, click Modify.
3.       Deselect the feature “Tools for Universal Windows App Development”
4.      Select “Tools for Universal Windows App Development” again, and click Update.
·         If you have already uninstalled the “Tools for Universal Windows Apps Development”:
·         Reinstall “Tools for Universal Windows App Development”
·         Or, take the following steps to reinstall the JavaScript project system and language service:
§  Download the installer for your edition of Visual Studio, e.g., vs_community.exe.
§  Open a CMD window, and run the following command: vs_community.exe /modify /installselectableitems JavaScript_Hidden /passive


https://social.msdn.microsoft.com/Forums/en-US/147cd1a2-1f1a-4847-a256-0613cfea732d/rtm-known-issue-visual-studio-hangs-when-creating-a-new-cordova-project-or-intellisense-doesnt?forum=Win10SDKToolsIssues
