### ISSUE TITLE
[iOS] Detecting release build in Cordova hook

### ISSUE THREAD

**Issue by omnight** [Microsoft/TACO#298]
When compiling for Android, I can check the cordova environment variable CORDOVA_CMDLINE to check if the build is being built in release mode, but that variable instead contains "/usr/local/bin/node /users/apps/.taco_home/node_modules/taco-remote-lib/2.2.0/node_modules/taco-remote-lib/ios/iosbuild.js" when I use remotebuild. 

How can I detect if I am running a release build?

**Comment by MSLaguana** [comment]
If you are writing your hook in javascript according to https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/#javascript then the `context` object passed in will have an `opts` property, and that should have either a `debug` or `release` property, which we set https://github.com/Microsoft/TACO/blob/master/src/taco-remote-lib/common/builder.ts#L264

If your hooks are not written in javascript, then I don't believe there is currently a way to pass that information to the scripts I'm afraid.

**Comment by omnight** [comment]
Thanks for the quick response. I have tried your suggestion and changed the hook to the new javascript method, but the context.opts looks like this:

```
{
	"platforms" : ["ios"],
	"projectRoot" : "/Users/Apps/.taco_home/remote-builds/taco-remote/builds/2692/cordovaApp",
	"cordova" : {
		"platforms" : ["ios"],
		"plugins" : [ ... ],
		"version" : "6.1.1"
	},
	"verbose" : false,
	"options" : {
		"buildConfig" : "/Users/Apps/.taco_home/remote-builds/taco-remote/builds/2692/cordovaApp/build.json"
	},
	"paths" : ["/Users/Apps/.taco_home/remote-builds/taco-remote/builds/2692/cordovaApp/platforms/ios/www"]
}
```
I have installed the latest remotebuild, and builder.js seems to contain the lines for release/debug flags but they don't seem to be set in my after_prepare hook. Am I doing something wrong?

**Comment by MSLaguana** [comment]
Which version of cordova are you targeting?

**Comment by MSLaguana** [comment]
I just tested this out against cordova 6.1.1 and it seemed to work, my context.opts.options was `{"debug":true,"emulator":true,"argv":""}`. If I then added a build.json to my project as well, it was present along with the other options too.

**Comment by omnight** [comment]
Thank you! The problem was that I was using cordova 5.3.3, which did not provide the "options" field, after updating to 6.2.0 I am getting the correct results.
