### ISSUE TITLE
Where is the build output for ios?

### ISSUE THREAD

**Issue by robinchesterman** [Microsoft/TACO#300]
I've set up a macincloud instance, I'm running 

`taco build ios`

It says the build was successful, but there's no sign of any build output on my Windows machine?

**Comment by MSLaguana** [comment]
I assume that you did `taco remote add ios` on your windows machine, and then configured it to point to remotebuild running on the macincloud instance?

If you ran `taco build ios` then by default we build for the iOS simulator, so you can test the app out on the machine running remotebuild. To get the build output on windows you must make sure to build for `--device`, and then the output should be in a `remote\ios\debug` folder.

**Comment by robinchesterman** [comment]
Great, thank you.
