### ISSUE TITLE
TACO live reload

### ISSUE THREAD

**Issue by mrvamsidhar** [Microsoft/TACO#301]
Hi, I am currently developing Hybrid app using TACO .When ever I do some changes to my source code, to see its effect every time I need to run "<taco run andoird>" command. This is pain. For every minor changes I need to run this command and wait for device getting new build. TACO live reload is not working. I always end up with some exception. Not sure how many of you having is facing this issue. If so, is there any way to update my code quickly?

**Comment by MSLaguana** [comment]
We are deprecating taco and recommend using our [vscode extension](https://marketplace.visualstudio.com/items?itemName=vsmobile.cordova-tools) for livereload, using ionic or cordova-simulate
