### ISSUE TITLE
"taco remote add ios" errors with "TACO5615: Error: unable to find certificate."

### ISSUE THREAD

**Issue by Klors** [Microsoft/TACO#302]
For some reason to do with my powershell profile, running `taco remote add ios` at the command line fails to connect to my remotebuild Mac. It resets the command window and then outputs `TACO5615: Error: unable to find certificate.`.

On the Mac side I can see that the first request goes to the remotebuild server and returns with a status 200, but the second command (that I could see was happening when I connected a project from Visual Studio) never actually gets called.

The reason I think it's to do with my powershell profile is that when I comment out my entire powershell `profile.ps1` script, the command then works.

I normally work in a powershell console and the only reason I thought to even try commenting it out is because, after a long time trying to get the remotebuild set up on the taco client side in powershell, I went to a normal dos command window to see if it was the same there and when I ran the command `taco remote add ios` and filled in the details the command window cleared and my powershell profile's custom command line prompt appeared in the dos window!

Why is this taco command causing my powershell profile script to be run after it does the intial request with the PIN, but before it gets the certificate?

Posting my entire powershell profile isn't possible, but I can tell you that among other things such as creating a bunch of custom commands and aliases, it does a `cls`, outputs a text banner to the console and defines a custom prompt (which it doesn't do if it thinks it's being run from the Nuget Console).

**Comment by MSLaguana** [comment]
When running taco-cli on windows we store the SSL certificate in the windows certificate store, and we do that via a powershell script https://github.com/Microsoft/TACO/blob/master/src/taco-cli/cli/remoteBuild/win32/certificates.ps1 which we invoke via https://github.com/Microsoft/TACO/blob/master/src/taco-cli/cli/remoteBuild/connectionSecurityHelper.ts#L34

When we fetch the SSL certificate for later use, we assume that the output of that command is exactly the ssl certificate, so if running the script triggers your text banner then that sounds like the cause.

**Comment by Klors** [comment]
Thanks for the reply @MSLaguana . It looks like the fix would be to change the options array specified to the spawn to include the `-NoProfile` switch.

I did try and clone the repository with a view to testing a fix for a PR, but the TACO repo seems to have a few issues with being built, and running the tests produces many pages of errors.
