### ISSUE TITLE
Joint effort for plugins/platforms compatibility matrix

### ISSUE THREAD

**Issue by slorber** [Microsoft/TACO#305]
Hi,

I'm not using TACO atm (as I already have a complex legacy Cordova project) but I think the "Kit" idea is nice.

Wouldn't it be better to make a community project just around those kits and separate it from TACO?

I think many people struggle with compatibility of platforms/plugins, and yes, upgrading is really painful (I'm trying to upgrade to ios platform 4.x and it's complicated...)

I don't know which form it can take exactly but it would be nice that every cordova developer can benefit from your experience of building these kits. For example, I'll probably take the versions of your latest kits for my next release, and I'll probably revert to ios 3.9.2, as it seems you did not make any kit with 4.x. I wouldn't be aware of those kits if I didn't take a better look at TACO documentation.

Also it would be nice to be able to discuss compatibility versions of non-official plugins (for example I would be interested by push/intercom plugins as well)

I've seen this Cordova matrix but it does not really talk about versions
https://cordova.apache.org/docs/en/latest/guide/support/

There's also this effort from Telerik to verify plugins:
http://plugins.telerik.com/cordova

So I don't really know what is actionnable about this issue, but I think releasing compatibility matrix documentation would be really helpful to the community, and you seem to have build some foundations for that. 

I've seen Microsoft investing more and more in Cordova community with TACO, CodePush or Ace.
But it's a huge work to review all versions of all plugins (even for Microsoft) so it should probably be crowdsourced with some system with ratings/comments/kit proposal. 

What do you think? Could Microsoft take the lead on such a project and ask other strong community actors to join?

**Comment by MSLaguana** [comment]
I believe that the idea of kits has moved over to cordova itself, where plugins can specify what version of cordova / platforms they work with.
