### ISSUE TITLE
Can't use file uri in vcordova parameter

### ISSUE THREAD

**Issue by cjpearson** [Microsoft/TACO#307]
When submitting a build request with `vcordova=file:///usr/local/lib/node_modules/cordova` it fails with the following error

```
null: Error: file:///usr/local/lib/node_modules/cordova is an invalid cordova version
```

**Comment by MSLaguana** [comment]
We only support `vcordova` values which are valid semver identifiers. Typically we `npm install cordova@<vcordova>` and keep that in a cache stored at `~/.taco_home/node_modules/cordova/<vcordova>`.

If you are trying to use a custom cordova version, you can use the above knowledge to your advantage: On the machine running remotebuild, navigate to `~/.taco_home/node_modules/cordova` and create a folder `x.y.z-custom` or similar, with a semver valid name. Inside that folder, create another `node_modules` folder, and then `npm install` your custom build. Now if you submit a build using that same `vcordova=x.y.z-custom` version, it will find that newly installed copy and build with it.

**Comment by gregvis** [comment]
the problem i am having is that vcordova isn't being parsed properly in CordovaWrapper.getCordovaVersion(). For me it is returning "6.3.1\r" which throws an error on the remotebuild machine. Can you update to parse out the "\r"

**Comment by MSLaguana** [comment]
We are deprecating this repository. If you feel strongly about this feature, please open an issue on https://github.com/microsoft/remotebuild
