### ISSUE TITLE
Package Cordova app doesn't work

### ISSUE THREAD

**Issue by neridonk** [Microsoft/TACO#311]
I followed the steps in this tutorial 

https://taco.visualstudio.com/en-us/docs/tutorial-package-publish-readme/#package-the-android-version-of-your-app

but my release folder is empty.

I have installed node js with Version 4.4.7
Cordova version  6.1.1

The build.bat in the \platforms\android\cordova folder

results in a 

`failed to find android_home environment variable
`
failed to find android command int your PATH

I could fix this error with the post in here
http://stackoverflow.com/questions/32454132/error-while-building-android-platform-at-cmd

**But how could this happen, what went wrong ?**

My Output 

```
1>------ Build started: Project: PumpiPumpPup, Configuration: Debug Android ------
1>  ------ Ensuring correct global installation of package from source package directory: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\APACHECORDOVATOOLS\packages\vs-tac
1>  ------ Name from source package.json: vs-tac
1>  ------ Version from source package.json: 1.0.42
1>  ------ Package already installed globally at correct version.
1>  ------ Cordova tools 6.1.1 already installed.
1>  ------ Build Settings:
1>  ------ Build Settings:
1>  ------    platformConfigurationBldDir: C:\Users\Dell\Documents\Visual Studio 2015\Projects\P\PumpiPumpPup\bld\Android\Release
1>  ------    platformConfigurationBinDir: C:\Users\Dell\Documents\Visual Studio 2015\Projects\P\PumpiPumpPup\bin\Android\Release
1>  ------    buildCommand: prepare
1>  ------    platform: Android
1>  ------    cordovaPlatform: android
1>  ------    configuration: Debug
1>  ------    cordovaConfiguration: Debug
1>  ------    projectName: PumpiPumpPup
1>  ------    projectSourceDir: C:\Users\Dell\Documents\Visual Studio 2015\Projects\P\PumpiPumpPup
1>  ------    npmInstallDir: C:\Users\Dell\AppData\Roaming\npm
1>  ------    language: en-US
1>  ------ Platform android already exists
1>  ------ Updating plugins
1>  ------ Currently installed plugins: cordova-plugin-whitelist@1.3.0
1>  ------ Currently installed dependent plugins:
1>  ------ Currently configured plugins:
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by ljzhong** [comment]
I don't understand how you are getting an error message and a successful Android build output. I suspect that your android_home no longer points to the Android SDK folder and that is why nothing is building. What is in the folder that android_home points to? It's a global env variable, or if you're using Visual Studio it can be found in the “Override Environmental Variables” pane in the Tools->Options->Tools for Apache Cordova menu. The folder should look something like this: 
![screen shot 2016-09-19 at 3 42 19 pm](https://cloud.githubusercontent.com/assets/8172288/18651376/bb63092e-7e7f-11e6-8f1a-941cab60df82.png)
