### ISSUE TITLE
Remotebuild doesn't work since I updated to xCode 8

### ISSUE THREAD

**Issue by mathishuettl** [Microsoft/TACO#312]
Hello,

since the update to iOS 10 and xCode 8 on my MacBook remotebuild doesn't work anymore.
Everytime I want to use remotebuild with Visual Studio 2015 I get the following errormessage:

> Severity    Code    Description    Project    File    Line    Suppression State
> Error        Remote build error from the build server Build failed with error Error code 65 for command: xcodebuild with args: -xcconfig,/Users/grafikschulung/.taco_home/remote-builds/taco-remote/builds/529/cordovaApp/platforms/ios/cordova/build-debug.xcconfig,-project,BlankCordovaApp1.xcodeproj,-target,BlankCordovaApp1,-configuration,Debug,-destination,platform=iOS,build,CONFIGURATION_BUILD_DIR=/Users/grafikschulung/.taco_home/remote-builds/taco-remote/builds/529/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/grafikschulung/.taco_home/remote-builds/taco-remote/builds/529/cordovaApp/platforms/ios/build/sharedpch: {1}    BlankCordovaApp1    C:\Users\m.hüttl\Desktop\BlankCordovaApp1\BlankCordovaApp1\MDAVSCLI    1

**Comment by MSLaguana** [comment]
Cordova-ios prior to version 4.3.0 doesn't support xcode 8. You can either upgrade your project to cordova-ios 4.3.0 (and save that configuration in your config.xml file), or you can follow the workaround instructions in https://dpogue.ca/articles/cordova-xcode8.html

Note that even if you do upgrade to cordova-ios 4.3.0, you will still need to add a `build.json` file with a `developmentTeam` setting as mentioned in the above link.

If you intend to debug your app on an iOS 10 device or simulator, you will also need to make sure the third party tools we use for that are up-to-date: `brew update && brew upgrade libimobiledevice --HEAD && brew upgrade ideviceinstaller ios-webkit-debug-proxy`

**Comment by mathishuettl** [comment]
Hello i've installed cordova in version 6.3.1
i already tryed the workarround, but it didn't work for me - still the same error.
Where i have to enter brew update command? on Windows?

**Comment by MSLaguana** [comment]
The error that you pasted above is a generic "The build failed" error, but if you go to the output pane you'll see the raw output, and if you scroll to the end and read up a little you should be able to see the actual error which caused the failure.

**Comment by MSLaguana** [comment]
If you are still facing this issue, please open an issue on the new repo https://github.com/microsoft/remotebuild since this repo is deprecated.
