### ISSUE TITLE
Deploying a Cordova app to iOS Devices results in error cod 65

### ISSUE THREAD

**Issue by zoinkydoink** [Microsoft/TACO#313]
I have posted the same issue on stackoverlfow, no solution yet

http://stackoverflow.com/questions/40458041/deploying-a-cordova-app-to-ios-devices-results-in-error-cod-65?noredirect=1#comment68200926_40458041

**Comment by MSLaguana** [comment]
If you are still facing this issue, please repost an issue on https://github.com/microsoft/remotebuild as this repository is deprecated.
