### ISSUE TITLE
CordovaError: Platform ios already added

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/TACO#316]
Hi Folks,

I created an SO question yesterday due to a build failure, didn't realize you all had a GIT repo.  It is described here.  
http://stackoverflow.com/questions/41030755/cordovaerror-platform-ios-already-added

Thanks
Jordan

**Comment by MSLaguana** [comment]
Hello Jordan, the VSTS integration is actually in a different repository, over at https://github.com/microsoft/vsts-cordova-tasks

That said, did you add the platforms folder to your source control? If you did, that might result in that error.

**Comment by jrmcdona** [comment]
Hi, I have platforms in my working directory but I do not have this in source control branch.

I can ask this question over in the correct repo.  Thanks!
