### ISSUE TITLE
Http 500: No devices found to debug. Please ensure that a device is connected and awake and retry.

### ISSUE THREAD

**Issue by stefdelec** [Microsoft/TACO#317]
I am trying to run on "remote device". I ping.

I just got this issue.

**Comment by MSLaguana** [comment]
This repository is deprecated and not actively maintained. Please refer to https://github.com/microsoft/remotebuild which is the new repository. Open an issue over there (so others who may have the same problem can benefit) and we'll troubleshoot what's going on.
