### ISSUE TITLE
Remote-Test Failed

### ISSUE THREAD

**Issue by megazoor** [Microsoft/TACO#318]
I was able to remotebuild just fine until recently... Visual studio gets all the way to the end of building the project and kicks it back because of supposed signing issues... 

I also realized i am unable to remotebuild test --device on the mac either... it fails with:
--------------------------------------------------------------------------------------------------------------------
`Error: taco-remote test failed.
Build Failed: {"vcordova":"5.4.0","vcli":"1.3.5","cfg":"debug","command":"build","options":"--device","status":"Error","buildCommand":"build","buildPlatform":"ios","configuration":"debug","buildDir":"/Users/UserName/.taco_home/remote-builds/taco-remote/builds/8859","buildNumber":8859,"logLevel":0,"submissionTime":"2016-12-19T07:04:33.780Z","changeList":null,"buildSuccessful":false,"messageId":"BuildFailedWithError","messageArgs":["/Users/UserName/.taco_home/remote-builds/taco-remote/builds/8859/cordovaApp/platforms/ios/cordova/build: Command failed with exit code 2"],"message":"Build failed with error /Users/UserName/.taco_home/remote-builds/taco-remote/builds/8859/cordovaApp/platforms/ios/cordova/build: Command failed with exit code 2","tgzFilePath":"/Users/UserName/.taco_home/remote-builds/taco-remote/builds/8859/upload_8859.tgz","appDir":"/Users/UserName/.taco_home/remote-builds/taco-remote/builds/8859/cordovaApp","statusTime":"2016-12-19T07:04:40.444Z","appName":"HelloCordova"}
/usr/local/lib/node_modules/remotebuild/node_modules/taco-utils/node_modules/applicationinsights/AutoCollection/Exceptions.js:25
                    throw error;
                          ^
Error: Build Failed: {"vcordova":"5.4.0","vcli":"1.3.5","cfg":"debug","command":"build","options":"--device","status":"Error","buildCommand":"build","buildPlatform":"ios","configuration":"debug","buildDir":"/Users/UserName/.taco_home/remote-builds/taco-remote/builds/8859","buildNumber":8859,"logLevel":0,"submissionTime":"2016-12-19T07:04:33.780Z","changeList":null,"buildSuccessful":false,"messageId":"BuildFailedWithError","messageArgs":["/Users/UserName/.taco_home/remote-builds/taco-remote/builds/8859/cordovaApp/platforms/ios/cordova/build: Command failed with exit code 2"],"message":"Build failed with error /Users/UserName/.taco_home/remote-builds/taco-remote/builds/8859/cordovaApp/platforms/ios/cordova/build: Command failed with exit code 2","tgzFilePath":"/Users/UserName/.taco_home/remote-builds/taco-remote/builds/8859/upload_8859.tgz","appDir":"/Users/UserName/.taco_home/remote-builds/taco-remote/builds/8859/cordovaApp","statusTime":"2016-12-19T07:04:40.444Z","appName":"HelloCordova"}
    at Request._callback (/usr/local/lib/node_modules/remotebuild/node_modules/taco-remote/lib/selftest.js:104:46)
    at Request.self.callback (/usr/local/lib/node_modules/remotebuild/node_modules/taco-remote/node_modules/request/request.js:121:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/remotebuild/node_modules/taco-remote/node_modules/request/request.js:985:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/remotebuild/node_modules/taco-remote/node_modules/request/request.js:936:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
`
--------------------------------------------------------------------------------------------------------------------

Any help would be amazing, I am incredible stuck here... Thank you!!!! <3

**Comment by MSLaguana** [comment]
This repository is deprecated in favor of https://github.com/microsoft/remotebuild

Could you please re-open this issue in that repository, and also include information on what version of Xcode you have installed? If you recently upgraded from Xcode 7 to Xcode 8 then there is an additional step you need to do (and we didn't add that into the self-test since it requires additional information from you to work)

**Comment by juanfcoespin** [comment]
hi
i have 8.3.3 version of xcode and have the same problem.
Could you explain what is the aditional step that you refer? I realy apreciate your contribution.
