### ISSUE TITLE
VS Taco with Cordova 7.x

### ISSUE THREAD

**Issue by ChrSveistrup** [Microsoft/TACO#327]
If you update the Cordova Toolset to 7.x the latest VS2017 update (v15.5.6) keeps complaining when you open the solution and set the Toolset version back to 6.3.1.

**Comment by drewgillies** [comment]
Hi--6.3.1 is the only supported version in VS 2017.

**Comment by hamburml** [comment]
This is so sad. Xamarin got some new cool and extremely important features (like the SDK Manager, Virtual Device Support, https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk) and Tools for Apache Cordova (btw, TACO needs the exact same thing, I don't understand why this was added only for xamarin) is thrown away. TACO simply only works with Android API 23 and an old Android SDK. When the used SDK is updated (build-tools, sdk-tools, ...) via Android Studio or the new Xamarin SDK Manager, TACO stops working, can't start the android emulator and just tries to install Android API SDK 23.
