### ISSUE TITLE
Installing tacokit doesn't update vs:plugin in config.xml

### ISSUE THREAD

**Issue by arangas** [Microsoft/TACO#36]
Hello. I just installed taco 1.0.0 and run the command to install tacokit@2.0.0 on my VS Cordova project. I noticed that it has added the line `<plugin name="cordova-plugin-file" spec="~3.0.0" />` to config.xml but left the old VS reference untouched as `<vs:plugin name="cordova-plugin-file" version="2.1.0" />`.

**Comment by subhagpo** [comment]
Hey Alex, 

Thanks for using TACO and pointing out this issue to us. 

Once you use CLI and have installed the tacokit@2.0.0 on your VS project, it would add the plugins that are contained in the kit and save those versions in the config.xml. If you want to continue using this kit-plugin then you should delete the <vs:plugin/> entry from config.xml. If you don't delete the entry, then VS honors the <vs:plugin/> setting to add the corresponding version of the plugin. 

We have captured this issue on our side to investigate if can improve interoperability between taco-kits and VS.

Thanks, once again!
