### ISSUE TITLE
Expose taco functionality as gulp tasks

### ISSUE THREAD

**Issue by mobidev111** [Microsoft/TACO#49]
Idea / feature request: Add gulp tasks for the taco functionality, so that I can integrate it into our gulp-based build process.

interesting gulp tasks would be for example:
taco:build
taco:build:ios
taco:build:android
taco:build:windows
taco:release
taco:release:ios
taco:release:android
taco:release:windows

**Comment by nisheetjain** [comment]
I like the idea. but you can do this today, using taco exposed API.
For e.g. you can write tasks like this to achieve what you need here. Essentially just call runTacoCommand here with whatever taco command you want to expose as gulp task

var gulp = require("gulp");
var taco = require("taco-cli");
var Q = require("q");

gulp.task("default", ["taco:build:android"]);

gulp.task("taco:platform:android", [], function () {
    return runTacoCommand("platform add android");
});

gulp.task("taco:build:android", ["taco:platform:android"], function () {
    return runTacoCommand("build android");
});

function runTacoCommand(command){
    return taco.runWithParsedArgs(taco.parseArgs(command.split(" ")));
}
module.exports = gulp;
