### ISSUE TITLE
'taco run' silently fails on Linux

### ISSUE THREAD

**Issue by omefire** [Microsoft/TACO#66]
Steps to repro:
- taco create proj
- cd proj
- taco run android

Behavior:
- does nothing

Expected:
- downloads and install android platform, then runs it.

Stepping through the code with node-inspector, I get the following error message: 
"Error: Cannot find module './utils/CordovaWrapper'"

**Comment by MSLaguana** [comment]
Agh, another file casing issue.

**Comment by MSLaguana** [comment]
taco-cli should work now. The tests are passing for me on an Ubuntu box.
