### ISSUE TITLE
'remotebuild test --secure false' fails - Yosemite/Cordova 5.3.3

### ISSUE THREAD

**Issue by kierer** [Microsoft/TACO#69]
I tried under Node 4.1.2 and then tried dropping back to 0.12.7, with the same result:

BuildMac:~ kierer$ remotebuild test --secure false
Remote build server listening on [http] port 3000
Please view/edit server configuration at /Users/kierer/.taco_home/RemoteBuild.config. You many need to run 'remotebuild saveconfig' to generate it. You will have to restart the server if you update the server configurations.
New build request submitted:
/build/tasks/?vcordova=4.3.0&vcli=1.1.0&cfg=debug&command=build&options=--emulator
{ host: 'buildmac.local:3000',
  connection: 'close',
  'transfer-encoding': 'chunked' }
Build will be executed under: /Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000
Saving build request payload to : /Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000
Saved uploaded build to /Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000/upload_1000.tgz
POST /cordova/build/tasks/?vcordova=4.3.0&vcli=1.1.0&cfg=debug&command=build&options=--emulator 202 244.372 ms - 654
Extracted app contents from uploaded build request to /Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000/cordovaApp. Requesting build.
Taking 1000 as current build
Done with current build. Checking for next build in queue.
1...
GET /cordova/build/tasks/1000 200 6.762 ms - 970
Error: taco-remote test failed.
[Error: Build Failed: {"vcordova":"4.3.0","vcli":"1.1.0","cfg":"debug","command":"build","options":"--emulator","status":"Error","buildCommand":"build","buildPlatform":"ios","configuration":"debug","buildDir":"/Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000","buildNumber":1000,"logLevel":-1,"submissionTime":"2015-10-07T21:52:52.603Z","changeList":null,"buildSuccessful":false,"messageId":"BuildFailedWithError","messageArgs":["/Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000/cordovaApp/platforms/ios/cordova/build: Command failed with exit code 2"],"message":"Build failed with error /Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000/cordovaApp/platforms/ios/cordova/build: Command failed with exit code 2","tgzFilePath":"/Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000/upload_1000.tgz","appDir":"/Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000/cordovaApp","statusTime":"2015-10-07T21:52:55.164Z","appName":"HelloCordova"}]
/usr/local/lib/node_modules/remotebuild/node_modules/q/q.js:126
                    throw e;
                          ^
Error: Build Failed: {"vcordova":"4.3.0","vcli":"1.1.0","cfg":"debug","command":"build","options":"--emulator","status":"Error","buildCommand":"build","buildPlatform":"ios","configuration":"debug","buildDir":"/Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000","buildNumber":1000,"logLevel":-1,"submissionTime":"2015-10-07T21:52:52.603Z","changeList":null,"buildSuccessful":false,"messageId":"BuildFailedWithError","messageArgs":["/Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000/cordovaApp/platforms/ios/cordova/build: Command failed with exit code 2"],"message":"Build failed with error /Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000/cordovaApp/platforms/ios/cordova/build: Command failed with exit code 2","tgzFilePath":"/Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000/upload_1000.tgz","appDir":"/Users/kierer/.taco_home/remote-builds/taco-remote/builds/1000/cordovaApp","statusTime":"2015-10-07T21:52:55.164Z","appName":"HelloCordova"}
    at Request._callback (/usr/local/lib/node_modules/remotebuild/node_modules/taco-remote/lib/selftest.js:86:45)
    at Request.self.callback (/usr/local/lib/node_modules/remotebuild/node_modules/taco-remote/node_modules/request/request.js:121:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/remotebuild/node_modules/taco-remote/node_modules/request/request.js:985:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/remotebuild/node_modules/taco-remote/node_modules/request/request.js:936:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by MSLaguana** [comment]
It sounds like your mac machine may not be configured correctly. Could you look at `~/.taco_home/remote-builds/taco-remote/builds/1000/build.log` if that file exists and see what it says? Alternately, what happens when you try to do a "cordova build ios" on the mac, does that succeed?

**Comment by kierer** [comment]
Thank you for the quick reply and pointing me to the log file- you are spot-on. I have multiple Xcode installs in non-standard folders. The log file showed:

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

running the following did the trick:

sudo xcode-select -s /Applications/xcode7.app/Contents/Developer

Thanks again!
K

**Comment by MSLaguana** [comment]
No problem, and this is exactly what `remotebuild test` is for, finding these kind of configuration issues. Glad you got things working!
