### ISSUE TITLE
building - Updating iOS platform.

### ISSUE THREAD

**Issue by softwarejc** [Microsoft/TACO#76]
The build never ends.

I get always always this message in visual studio 2015: (it run for more than 2 hours)

Checking on build status from http://X.X.X.X:3000/cordova/build/tasks/3781 [Attempt XX]
1>  building - Updating iOS platform

The last message of the build.log on my mac is:
Attempt to update xcode project: /Users/juasan00/.taco_home/remote-builds/taco-remote/builds/3159/cordovaApp/platforms/ios/ROOMobile.xcodeproj/project.pbxproj

I have now xcode7, before I had xcode6 and had the same issue.
I tried already to uninstall-install and update everything... any idea how to fix this?

Thank you!

**Comment by MSLaguana** [comment]
What version of nodejs are you running on the mac with remotebuild? There is a known issue in cordova under nodejs 4.X where if you have certain options specified in config.xml, the build process won't finish correctly. When using cordova directly this shows up as the build terminating immediately, but when this happens in remotebuild it shows up as a hung process waiting for an event that will never happen.

Until Cordova comes up with a solution your best bet is to revert back to nodejs version 0.12.7, or you can make sure that your config.xml does not specify any preferences relating to iOS version or whether it is for phone or tablet.

**Comment by softwarejc** [comment]
Thank you! it works with nodejs 0.12.7
