### ISSUE TITLE
RemoteBuild Hangs with Node 4.0

### ISSUE THREAD

**Issue by nisheetjain** [Microsoft/TACO#96]
Issue was reported by a customer here
http://stackoverflow.com/questions/33225961/ios-remote-build-infinite-attempt-on-visual-studio-cordova/33247768#33247768

Taco should proactively detect the scenario and fail the build with clear error messages

**Comment by MSLaguana** [comment]
We've got the error message in now and we won't deadlock remotebuild anymore, so I'm closing this issue.
